### ISSUE TITLE
使用libtorch的时候，加载gpu会报错

### ISSUE THREAD

**Issue by ww451575464** [modelscope/FunASR#1024]
在使用model = Paraformer(model_dir, batch_size=1, device_id=0) 加载权重之后，在进行识别的时候，无论什么输入，都会打印
input wav is silence or noise
在libtorch\funasr_torch中查看paraformer_bin.py，打开except中的错误提示注释，此时再次进行识别，报出的具体错误是two device
出现在outputs = self.ort_infer(feats.cuda(), feats_len.cuda())这里

请问这个项目是不支持gpu加速么

**Comment by LauraGPT** [comment]
For the gpu usage, you should export torchscripts on gpu and keep the envs same.

**Comment by ww451575464** [comment]
我是执行以下语句来转换pb模型
python -m funasr.export.export_model --model-name damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch --export-dir ./export --type torch --quantize True

应该怎么改呢

**Comment by TengLi931128** [comment]
我也遇到同样的问题，请问您解决了么？
