### ISSUE TITLE
Issue with Stage 1: Feature and CMVN Generation in Speech Recognition script

### ISSUE THREAD

**Issue by qiulin13145** [modelscope/FunASR#1058]
**Issue:**
I'm following the instructions from the "Speech Recognition" documentation and I'm facing an issue when executing `bash run.sh`. I was able to pass stage 0 successfully, but the script seems to get stuck at stage 1. 

**Steps to reproduce:**
1. Run `bash run.sh`

**Expected result:**
The script should proceed past stage 1.

**Observed result:**
The script gets stuck at stage 1 with no further output. Upon investigation, I found that the script is stuck at line 311 in `run.pl`, and the corresponding subprocess remains in the 'S' (Sleeping) state. 
![1](https://github.com/alibaba-damo-academy/FunASR/assets/144438757/83699167-ff36-4d85-b405-6e649e735e90)

![image](https://github.com/alibaba-damo-academy/FunASR/assets/144438757/9469df2e-2434-44db-bd43-0ba63592fc49)

![image](https://github.com/alibaba-damo-academy/FunASR/assets/144438757/61a4507f-0a04-49a3-b830-c3de7c5e4c65)

**Question:**
I'm unsure about the cause of this issue. I would appreciate any guidance or help in resolving it. Thanks in advance!

**Comment by LauraGPT** [comment]
Maybe you could change the code and try it again, in `egs/aishell/paraformer/utils/apply_cmvn.sh` line 20:

```shell
#$cmd JOB=1:$nj $logdir/apply_cmvn.JOB.log \
#    python utils/apply_cmvn.py -a $fbankdir/ark/feats.JOB.ark \
#        -c $cmvn_file -i JOB -o ${dump_dir} \
#        || exit 1;

for JOB in `seq 1 $nj`;do
  {
      python utils/apply_cmvn.py -a $fbankdir/ark/feats.${JOB}.ark \
    -c $cmvn_file -i ${JOB} -o ${dump_dir} || exit 1;
  } &> $logdir/apply_cmvn.${JOB}.log
done
```

**Comment by qiulin13145** [comment]
Thank you for your response. Unfortunately, despite my attempts, I'm still running into the same issues and errors as before. Do you have any other suggestions or solutions?
