### ISSUE TITLE
VAD pipeline doesn' auto resampling the input audio which ASR pipeline does.

### ISSUE THREAD

**Issue by oxyhexagen** [modelscope/FunASR#1060]
OS: Ubuntu 20.04

Python/C++ Version：python 3.10

Package Version：
pytorch 2.1.0+cu118、torchaudio 2.1.0+cu118、modelscope 1.9.4、funasr 0.8.2

Model：VAD-speech_fsmn_vad_zh-cn-16k-common-pytorch-v1.2.0

Command：
```python
vad = pipeline(
        task=Tasks.voice_activity_detection,
        model="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch",
        model_revision=None
    ) 
res = vad(audio_in=my_audio_path)
```

Details：
When the program runs to build the dataloader providing iterator for training batches:
https://github.com/alibaba-damo-academy/FunASR/blob/8c904ecadde91d19d97a011377cc978459d601ce/funasr/bin/vad_inference_launch.py#L88-L96
The incoming parameter 'fs' used for guiding resampling is missing by default, resulting in the VAD program not resampling the input audio to 16000, while all kinds of the ASR pipeline does pass a value to 'fs':
https://github.com/alibaba-damo-academy/FunASR/blob/8c904ecadde91d19d97a011377cc978459d601ce/funasr/bin/asr_inference_launch.py#L345-L354
Refer to the figure below for better comparison:
![2023-11-06 10-18-41 的屏幕截图](https://github.com/alibaba-damo-academy/FunASR/assets/29267562/e712ce0b-9bd9-49a5-855c-181d4fd78f58)
Error log：
So when an input WAV audio with a sampling rate of 44100 is provided, the dataloader will pass a tensor sampled at 44100 to VAD. The resulting output does not match the audio at all :
![2023-11-06 09-49-39 的屏幕截图](https://github.com/alibaba-damo-academy/FunASR/assets/29267562/3fdc9a5a-1fd5-4ea4-ac4d-e140349445f4)
Properties of the input audio:
![2023-11-06 09-29-36 的屏幕截图](https://github.com/alibaba-damo-academy/FunASR/assets/29267562/6641d7d4-985f-43e6-addb-2670b38de07a)
Vad result(timestamps may exceed the audio length):
![2023-11-06 09-30-58 的屏幕截图](https://github.com/alibaba-damo-academy/FunASR/assets/29267562/d95e98c2-7210-4211-a258-727e28a81dc0)

Based on my limited tests, passing the 'fs' parameter in the dataloader (like in the ASR pipeline) does not seem to cause any issues, the results were as expected and correct..

**Comment by hnluo** [comment]
Bug has been fixed, please update funasr([1062](https://github.com/alibaba-damo-academy/FunASR/pull/1062))
