### ISSUE TITLE
微调后模型speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch后，推理无输出

### ISSUE THREAD

**Issue by linshoubiao** [modelscope/FunASR#1061]
微调模型后，加载./checkout微调输出目录下模型，无推理结果，用训练集测试也无结果。code如下：

infer_params = {}
    infer_params["model_dir"] = "/workspace/asr/FunASR/egs_modelscope/asr_vad_punc/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/checkpoint"
    infer_params["decoding_model_name"] = "10epoch.pb"
    infer_params["test_data_dir"] = "/workspace/asr/FunASR/egs_modelscope/asr_vad_punc/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/data/validation"
    modelscope_infer(infer_params)

**Comment by linshoubiao** [comment]
OS: e.g. linux
Python/C++ Version：3.8.18
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
torch                    2.0.1
torchaudio               2.0.2
modelscope               1.9.4
funasr                   0.8.2
Model：speech_paraformer-large-vad-punc_asr
Command：
Details：
其中 --model文件目录是原始的预训练模型路径，其中的model.pb 是微调后19epoch.pb靠过来改成model.pb的
def modelscope_infer(args):
    os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpuid)
    inference_pipeline = pipeline(
        task=Tasks.auto_speech_recognition,
        model=args.model,
        output_dir=args.output_dir,
        batch_size=args.batch_size,
        update_model=False,
        param_dict={"decoding_model": args.decoding_mode, "hotword": args.hotword_txt}
    )
    rlst = inference_pipeline(audio_in=args.audio_in)
    print("rlst")
    print(rlst)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', type=str, default="/workspace/asr/FunASR/egs_modelscope/asr_vad_punc/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/checkpoint")
    parser.add_argument('--audio_in', type=str, default="/workspace/data/asr-data/asr_data_1000-1101/asr_data_1000-1101/74_2021111203.wav_12.wav")
    parser.add_argument('--output_dir', type=str, default="./results/")
    parser.add_argument('--decoding_mode', type=str, default="normal")
    parser.add_argument('--hotword_txt', type=str, default=None)
    parser.add_argument('--batch_size', type=int, default=4)
    parser.add_argument('--gpuid', type=str, default="1")
    args = parser.parse_args()
    modelscope_infer(args)


Error log：

**Comment by linshoubiao** [comment]
原始得预训练模型是在huggingface上[hezhaoqia](https://huggingface.co/hezhaoqia) / [speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch](https://huggingface.co/hezhaoqia/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch)下得。
微调过程中loss已经很低了，使用部分训练集合进行测试，没有输出，results = speech2text(**batch)中间结果全为 <unk> <unk> <unk>
funasr代码版本为dev_bat_modelscope

**Comment by h310558606** [comment]
遇到相似的问题，请问解决了吗？
