### ISSUE TITLE
请问下跑方言转译模型damo/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-offline，41分钟16k比特率的语音，跑了10分钟还没跑完这正常吗？

### ISSUE THREAD

**Issue by xuhongtian** [modelscope/FunASR#1078]
linux下，ubuuntu20.04版本，funasr=0.8.2,python=3.9，modelscope=1.9.4,使用4090跑的，41分钟的一段16k比特率的语音跑了十分钟依然显示还在解码没跑完，页面没提示报错，这个速度不太对吧？测试代码如下：
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
inference_pipeline_1 = pipeline(task=Tasks.auto_speech_recognition, model='damo/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-offline')
import time
start_time = time.time()
wav_name = "./2023110700000485.wav"
rec_result = inference_pipeline_1(audio_in = wav_name)
print("rec_result",rec_result)
#print("识别结果------",rec_result["text"])
end_time = time.time()
print("转译完成时间---",end_time - start_time)

**Comment by xuhongtian** [comment]
这是我的测试语音

**Comment by LauraGPT** [comment]
The max duration of UniASR is 15s. If your wav is longer, you should use a vad to split the wav into short slices. https://github.com/alibaba-damo-academy/FunASR/discussions/278
