### ISSUE TITLE
标点符号添加错误，书名号中内容被添加标点符号

### ISSUE THREAD

**Issue by RichardQin1** [modelscope/FunASR#1104]
使用标点符号添加模型进行处理， 书名号中内容被添加标点。
`
inference_pipline = pipeline(
        task=Tasks.punctuation,
        model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
        model_revision="v1.1.7")
tmp_str = "《内容测试》内容测试内容司内容"
inference_pipline(text_in=tmp_str)
`
输出结果：
《内容测试。》内容测试内容司内容

期望：
书名号中内容不要进行添加

**Comment by LauraGPT** [comment]
I have tested it with the ct-transformer large version, the result is expected. Maybe you could try it:

https://github.com/alibaba-damo-academy/FunASR/tree/main/egs_modelscope/punctuation/punc_ct-transformer_cn-en-common-vocab471067-large

**Comment by RichardQin1** [comment]
> I have tested it with the ct-transformer large version, the result is expected. Maybe you could try it:
> 
> https://github.com/alibaba-damo-academy/FunASR/tree/main/egs_modelscope/punctuation/punc_ct-transformer_cn-en-common-vocab471067-large

sorry, Let me update the sample content
