### ISSUE TITLE
自己训练的模型，inference结果为空

### ISSUE THREAD

**Issue by h310558606** [modelscope/FunASR#1109]
基于FunASR/egs进行模型训练，得到一个适用于小语种ASR的paraformer模型，然后将此模型训练得到的的模型文件和config文件替换掉damo/speech_paraformer_asr_nat-zh-cn-16k-aishell1-vocab4234-pytorch 下的模型文件与config文件，接下来使用如下代码进行推理：

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='models_from_modelscope/damo1/speech_paraformer_asr_nat-zh-cn-16k-aishell1-vocab4234-pytorch',
)
rec_result = inference_pipeline(audio_in='https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav')
print(rec_result)

**返回结果为空值！！！**

![image](https://github.com/alibaba-damo-academy/FunASR/assets/38098690/4d40d17f-c2bf-4289-9051-f3db8c8e6310)
![05(1)](https://github.com/alibaba-damo-academy/FunASR/assets/38098690/17ed9ad2-df1c-4313-a470-be5e15f31251)
![03](https://github.com/alibaba-damo-academy/FunASR/assets/38098690/730396ed-46e6-40c4-8149-856de9464955)

**Comment by LauraGPT** [comment]
Maybe the diff is `am.mvn`, please check it.

**Comment by h310558606** [comment]
> Maybe the diff is `am.mvn`, please check it.

I replaced the am.mvn file used for training, and the result was still the same. There was no inference output. When I printed the intermediate results, I found that the output was all unk characters.

**Comment by LauraGPT** [comment]
> > Maybe the diff is `am.mvn`, please check it.
> 
> I replaced the am.mvn file used for training, and the result was still the same. There was no inference output. When I printed the intermediate results, I found that the output was all unk characters.

Does you ever test the inference in the stage5:https://github.com/alibaba-damo-academy/FunASR/blob/main/egs/aishell/paraformer/run.sh#L157

**Comment by h310558606** [comment]
> > > Maybe the diff is `am.mvn`, please check it.
> > 
> > 
> > I replaced the am.mvn file used for training, and the result was still the same. There was no inference output. When I printed the intermediate results, I found that the output was all unk characters.
> 
> Does you ever test the inference in the stage5:https://github.com/alibaba-damo-academy/FunASR/blob/main/egs/aishell/paraformer/run.sh#L157

Yes, I run the stage 5, but get nothing.

The train log:
![train](https://github.com/alibaba-damo-academy/FunASR/assets/38098690/147b4664-6c48-4992-926a-8b0cfe853799)
The test log:
![test](https://github.com/alibaba-damo-academy/FunASR/assets/38098690/8e46e9b7-36ae-47e0-aed9-53d92c09ec0e)

**Comment by LauraGPT** [comment]
> > > > Maybe the diff is `am.mvn`, please check it.
> > > 
> > > 
> > > I replaced the am.mvn file used for training, and the result was still the same. There was no inference output. When I printed the intermediate results, I found that the output was all unk characters.
> > 
> > 
> > Does you ever test the inference in the stage5:https://github.com/alibaba-damo-academy/FunASR/blob/main/egs/aishell/paraformer/run.sh#L157
> 
> Yes, I run the stage 5, but get nothing.
> 
> The train log: ![train](https://user-images.githubusercontent.com/38098690/285370603-147b4664-6c48-4992-926a-8b0cfe853799.png) The test log: ![test](https://user-images.githubusercontent.com/38098690/285370651-8e46e9b7-36ae-47e0-aed9-53d92c09ec0e.png) ![image](https://user-images.githubusercontent.com/38098690/285371694-06737f18-39ac-4516-8e38-4d7595f5d3dc.png)


Please chech the inference log, and see what happens
