### ISSUE TITLE
modelscope 的pipeline 是否还不支持热词的热加载？

### ISSUE THREAD

**Issue by Amazing-J** [modelscope/FunASR#1143]
RT
例如这样：
asr_pipeline = pipeline(
            task=Tasks.auto_speech_recognition,
            model="damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404",
            vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
            punc_model='damo/punc_ct-transformer_cn-en-common-vocab471067-large',
            ngpu=1,
            batch_size=5000）

param_dict = dict()
param_dict['hotword'] = "短视频"
param_dict['clas_scale'] = 1.50
asr_pipeline(_samples, param_dict)

![image](https://github.com/alibaba-damo-academy/FunASR/assets/38121353/99e4fa4f-ea03-4770-a28a-2b0f750bdaad)

**Comment by wwfcnu** [comment]
batch_size可以设置成5000这么大吗
