### ISSUE TITLE
没有生成cmvn.json和am.mvn文件

### ISSUE THREAD

**Issue by sister-tong** [modelscope/FunASR#1150]
linux:Ubuntu 20.04.4
python=3.8.18
torch=2.0.1
funasr=0.8.2
modelscope=1.9.3
在训练模型的stage1，没有生成cmvn.json和am.mvn文件是什么原因啊，怎么排查这个错误

**Comment by LauraGPT** [comment]
We are re-designing the framework of FunASR. Please wait for serval days.
