### ISSUE TITLE
微调的数据格式支持segments吗

### ISSUE THREAD

**Issue by 1215thebqtic** [modelscope/FunASR#1167]
您好，

微调时的数据格式是text和wav.scp，我这里有的数据还有segments文件，即为音频其中的某一段，全部切成小文件有点浪费空间。所以数据格式可以支持segments吗？谢谢！

**Comment by LauraGPT** [comment]
Sorry, we do not have such plans. You can pre-process the audio by cutting it according to the segment information before proceeding with model training.
