### ISSUE TITLE
说话人darization报错

### ISSUE THREAD

**Issue by lucasjinreal** [modelscope/FunASR#1179]
File "C:\miniconda\Lib\site-packages\funasr\bin\diar_inference_launch.py", line 140, in _forward
    assert all([len(example) >= 2 for example in raw_inputs]), \
AssertionError: The length of test case in raw_inputs must larger than 1 (>=2).

必须输入两个文件？

**Comment by lmxin123** [comment]
请问你的说话人分离是怎么做的
