### ISSUE TITLE
paraformer 模型训练的时候如何扩充词汇表

### ISSUE THREAD

**Issue by yijinsheng** [modelscope/FunASR#1216]
### 主要是想训练这两个模型
- damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online
- damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch

原始需求是希望训练一个模型，同时支持多语种的识别（普通话，粤语，闽南语，英语等），现有的模型只支持一种或者其中的最多两种

**Comment by secslim** [comment]
请问找到扩充词表的方法了吗？
