### ISSUE TITLE
按照项目介绍将模型下载到本地，使用本地模型时，程序依然去下载模型。具体问题代码如下，请修复

### ISSUE THREAD

**Issue by tankchenggeng** [modelscope/FunASR#1219]
错误文件：modelscope\utils\audio\audio_utils.py
 
 `
    if model_config.__contains__('model'):
        model_name = model_config['model']
        dst_dir_root = get_cache_dir()
        **if isinstance(model_path, str) and os.path.exists(
                model_path) and not model_path.startswith(dst_dir_root)**:
            try:
                dst = os.path.join(dst_dir_root, '.cache/' + model_name)
                dst_dir = os.path.dirname(dst)
                os.makedirs(dst_dir, exist_ok=True)
                if not os.path.exists(dst):
                    os.symlink(os.path.abspath(model_path), dst)

                snapshot_download(
                    model_name,
                    cache_dir=dst_dir_root,
                    revision=model_revision)
            except Exception as e:
                logger.warning(str(e))
    else:
        logger.warning('Can not find model name in configuration')
`

模型存在但不在目标目录，应当执行复制而不是下载

**Comment by davids-dot** [comment]
怎么解决的？

**Comment by tankchenggeng** [comment]
> 怎么解决的？

os.environ["MODELSCOPE_CACHE"] = modelscope_path

将modelscope_cache的权重缓目录环境变量设置为你权重文件的根目录

**Comment by davids-dot** [comment]
谢谢大佬，我试试
