### ISSUE TITLE
recognizing in memory data recorded by pyaudio

### ISSUE THREAD

**Issue by lancemao** [modelscope/FunASR#1290]
Hi there,

Cool project! Very easy to get started. (can't get paddlespeech to work for days lol)

Wondering if FunASR can take audio frame data recorded by pyaudio as the input? Since this way, we don't need to save the data as .wav file. Peudo code (generated by ChatGPT) for pyaudio would be something like this:

```python
import pyaudio

# the following values are typical audio parameters
format = pyaudio.paInt16  # data type format
channels = 1  # 1 for mono
rate = 44100  # samples per second
chunk = 1024  # record in chunks of 1024 samples

# initializing PyAudio object
p = pyaudio.PyAudio()

# open stream
stream = p.open(format=format,
                channels=channels,
                rate=rate,
                input=True,
                frames_per_buffer=chunk)

print("Recording...")

try:
    while True:
        # read a chunk of data
        data = stream.read(chunk)

        # TODO: Here you can process the stream data
```

we can use such code, together with a very simple sliding window trick to implement a system that can do real time ASR

Thanks!

**Comment by LauraGPT** [comment]
It has been supported now. We would write example code sooner.

**Comment by LauraGPT** [comment]
We have a demo of websocket to send audio from microphone in client: https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/python/websocket/funasr_wss_client.py#L102

And the server receive the audio data to transcribe: https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/python/websocket/funasr_wss_server.py#L271
