### ISSUE TITLE
CT-Transformer标点模型的训练代码没有样例呢，求助！！！

### ISSUE THREAD

**Issue by lzl1456** [modelscope/FunASR#1384]
### Before asking:
1. search the issues.
2. search the docs.

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
On going

**Comment by lzl1456** [comment]
“”CT-Transformer标点-中英文-通用-large“”
这个CT-tranformer 标点的模型，并不是采用的看未来L长度呀，如果输入text_lengths按每条长度，里面代码就只乘了这个做成的mask，就是看全局的san_M， 有没有跟论文一样的配置代码模型呢？ 
还有该模型前向20切分输入，是否是最佳值呢

**Comment by 184653090** [comment]
我也想对标点模型进行微调，请问您实现了吗？

**Comment by chentiejin1** [comment]
这个微调现在开源了吗，还没有找到对应的训练脚本？
