### ISSUE TITLE
uniasr方言模型与vad 、punc模型一起使用时的bug

### ISSUE THREAD

**Issue by seanzhang-zhichen** [modelscope/FunASR#1436]
## ❓ Questions and Help

在钉钉群沟通过了，说是uniasr模型适配的问题，希望尽快能够解决

![1709105459028_F8371239-1841-4fd6-AB45-8B09CAD4AAE2](https://github.com/alibaba-damo-academy/FunASR/assets/74812416/00a2388d-a56e-424e-89e9-2722d975c810)

#### What have you tried?

阅读源码，已确定是模型问题

#### What's your environment?

 - linux
 - funasr                        1.0.10
 - ModelScope Version 1.12.0

**Comment by lanyuer** [comment]
同样遇到这个问题，只能降级使用

**Comment by seanzhang-zhichen** [comment]
> 同样遇到这个问题，只能降级使用

降级就不能和其他模型一起用了，比如说话者识别，标点恢复

**Comment by tramphero** [comment]
Sorry, we are currently unable to maintain the UniASR series of models.

**Comment by summerHearts** [comment]
> 同样遇到这个问题，只能降级使用

降级到哪个版本呢，老哥

**Comment by jinec** [comment]
@seanzhang-zhichen 兄弟，这个uniasr最后用了吗？小弟我现在也是要识别方言。不知道咋办
