### ISSUE TITLE
KeyError: 'FunASRPipeline: KeyError("GenericFunASR: \'config\'")'

### ISSUE THREAD

**Issue by suzhaoxi** [modelscope/FunASR#1448]
## ❓ Questions and Help

**运行时，提示：KeyError: 'FunASRPipeline: KeyError("GenericFunASR: \'config\'")'**

<img width="788" alt="4b923343b8a447e300b43523a3369749" src="https://github.com/alibaba-damo-academy/FunASR/assets/76837109/a53690a6-caea-481b-bf27-6ef5edf1cb87">

#### Code
`from modelscope.pipelines import pipeline`
`from modelscope.utils.constant import Tasks`

`AudioFile = 'D:/project/Paraformer/data/output.wav'`

`inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,`
`    model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',`
`    model_revision="v2.0.4")`

`rec_result = inference_pipeline(audio_in=AudioFile)`

`print(rec_result)`

#### What's your environment?

 - OS (Windows11):
 - FunASR Version (1.0.14):
 - ModelScope Version (1.11.1):
 - PyTorch Version (2.2.1):
 - How you installed funasr (pip):
 - Python version: 3.9.17
 - GPU (RTX4060)
 - CUDA/cuDNN version (CUDA 12.3.104 driver):
 - Docker version (null)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Please update modelscope and retry it again: pip install -U modelscope

Or you could use it directly by `AutoModel`:  https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/industrial_data_pretraining/bicif_paraformer/demo.py
