### ISSUE TITLE
runtime iOS Demo cannot compile successfully

### ISSUE THREAD

**Issue by summerHearts** [modelscope/FunASR#1454]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
The necessary files that the main branch depends on are deleted, resulting in failure to compile successfully.
#### Code
<img width="966" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/10678821/ec757fa0-9031-42ee-823f-38865953e763">
I saw several people asking this question, but no one paid attention.

#### What have you tried?
The necessary files that the main branch depends on are deleted, resulting in failure to compile successfully.
#### What's your environment?
iOS

**Comment by 601222543** [comment]
@LauraGPT @andyweiqiu I also encountered the same problem, can you help us?

**Comment by summerHearts** [comment]
It's been two months, can anyone fix the iOS issue?

**Comment by 601222543** [comment]
@summerHearts 自己重写一个吧😂

**Comment by lyblsgo** [comment]
Pull the latest code from Git.

**Comment by WangHanGYY** [comment]
> Pull the latest code from Git.

The problem still exists.

**Comment by jiangxkwj** [comment]
problem still
