### ISSUE TITLE
question for told model

### ISSUE THREAD

**Issue by freshpearYoon** [modelscope/FunASR#1508]
hi, thanks for your codes.
I am trying to use model of "TOLD : A novel two-stage overlap-aware framework for Speaker Diarization", but cannot find the model(Found only eend-ola code).
How can I experiment on only speaker diarization with this model , with out using other models?

**Comment by LauraGPT** [comment]
You could find it in v0.8.8 branch:
https://github.com/alibaba-damo-academy/FunASR/tree/v0.8.8/egs/callhome/TOLD
