### ISSUE TITLE
AliFsmnVad实例的GetSegments函数，返回的时间比实际时长多

### ISSUE THREAD

**Issue by greatbag** [modelscope/FunASR#1512]
复现条件，直接运行起来，通过AliFsmnVad实例的GetSegments函数，返回的时间比实际时长多
# #环境
-操作系统(如windows11):

FunASR版本最新版
Microsoft.ML.OnnxRuntime 最新版本:
![6e1c456dab532002bf6dd1b234f9f673](https://github.com/alibaba-damo-academy/FunASR/assets/35184007/e3a77313-568d-4038-8c25-1378df1d1b10)
![40dc654dea091a3b153bda89b35c4859](https://github.com/alibaba-damo-academy/FunASR/assets/35184007/ec5ad7bc-0491-4c65-9b54-8ef01b32aed3)
测试音频为speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch\example提供 的asr_example.wav

下载
https://www.modelscope.cn/models/iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/file/view/master/example%2Fasr_example.wav?status=0

**Comment by manyeyes** [comment]
示例音频13秒，vad推理结果如下：
vad infer result:
[[100,4690][5020,10030][10310,13030]]
elapsed_milliseconds:67.8515625
total_duration:13052
rtf:0.005198556734600061
建议用最新的源码再试试，或者检查一下bin目录中的测试文件与指定的是否一致。 @greatbag
