### ISSUE TITLE
KeyError: 'speaker-diarization-inference is not in the pipelines registry group speaker-diarization.

### ISSUE THREAD

**Issue by san-kou7** [modelscope/FunASR#1516]
🐛 Bug

when i run the code about-- quick_start_zh.md([FunASR](https://github.com/alibaba-damo-academy/FunASR/tree/main)/[docs](https://github.com/alibaba-damo-academy/FunASR/tree/main/docs)/[modelscope_pipeline](https://github.com/alibaba-damo-academy/FunASR/tree/main/docs/modelscope_pipeline)
/quick_start_zh.md)

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_diar_pipline = pipeline(
    mode="sond_demo",
    num_workers=0,
    task=Tasks.speaker_diarization,
    diar_model_config="sond.yaml",
    model='damo/speech_diarization_sond-en-us-callhome-8k-n16k4-pytorch',
    model_revision="v1.0.3",
    sv_model="damo/speech_xvector_sv-en-us-callhome-8k-spk6135-pytorch",
    sv_model_revision="v1.0.0",
)

audio_list=[
    "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_data/record.wav",
    "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_data/spk_A.wav",
    "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_data/spk_B.wav",
    "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_data/spk_B1.wav"
]

results = inference_diar_pipline(audio_in=audio_list)
print(results)
24-03-19 19:24:25,934 - modelscope - WARNING - ('PIPELINES', 'speaker-diarization', 'speaker-diarization-inference') not found in ast index file
Traceback (most recent call last):
  File "/home/caopinzhi/FunASR/try/two.py", line 4, in <module>
    inference_diar_pipline = pipeline(
  File "/home/caopinzhi/yes/envs/fun/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/caopinzhi/yes/envs/fun/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/home/caopinzhi/yes/envs/fun/lib/python3.9/site-packages/modelscope/utils/registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'speaker-diarization-inference is not in the pipelines registry group speaker-diarization. Please make sure the correct version of ModelScope library is used.'

### Environment
 -  Linux
 - FunASR Version (1.0.17):
 - ModelScope Version (1.13.1):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr ( source):
 - Python version:3.9

I hope you can help me solve this problem amidst your busy schedule. I would greatly appreciate it.

**Comment by LauraGPT** [comment]
Please install:
funasr==0.8.8
modelscope==1.10.0

**Comment by san-kou7** [comment]
Thank you very much for your answer, it successfully solved my above problem.But I encountered a similar problem when using the model on modelscope for inference.（iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn  https://www.modelscope.cn/models/iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn/summary）

Bug：KeyError: 'funasr-pipeline is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

Code：
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

if __name__ == '__main__':
    audio_in = 'https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_speaker_demo.wav'
    output_dir = "./results"
    inference_pipeline = pipeline(
        task=Tasks.auto_speech_recognition,
        model='iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn',
        model_revision='v2.0.4',
        vad_model='iic/speech_fsmn_vad_zh-cn-16k-common-pytorch', vad_model_revision="v2.0.4",
        punc_model='iic/punc_ct-transformer_cn-en-common-vocab471067-large', punc_model_revision="v2.0.4",
        output_dir=output_dir,
    )
    rec_result = inference_pipeline(audio_in, batch_size_s=300, batch_size_token_threshold_s=40)
    
    print(rec_result)

Traceback (most recent call last):
  File "/home/caopinzhi/FunASR/try/three.py", line 7, in <module>
    inference_pipeline = pipeline(
  File "/home/caopinzhi/yes/envs/fun/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/caopinzhi/yes/envs/fun/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/home/caopinzhi/yes/envs/fun/lib/python3.9/site-packages/modelscope/utils/registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'funasr-pipeline is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

Environment
Linux
FunASR Version (0.8.8):
ModelScope Version (1.10.0):
PyTorch Version (e.g., 2.0.0):
How you installed funasr ( source):
Python version:3.9

I greatly appreciate that help me solve this problem again.
