### ISSUE TITLE
调用funasr出现段错误

### ISSUE THREAD

**Issue by lonngxiang** [modelscope/FunASR#1546]
导入funasr包出现问题，这是什么原因呢，其他包正常

![image](https://github.com/alibaba-damo-academy/FunASR/assets/40717349/38d7e706-d3d8-4fd4-b9dc-c3ac7a333a07)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/40717349/223e93e3-1135-4071-ac9c-03d0caf496be)

**Comment by lyblsgo** [comment]
Let's close this issue for now. If needed, reopen it.
