### ISSUE TITLE
中文语音中夹带少量英语时英语单词可能会缺失，

### ISSUE THREAD

**Issue by lzdk2003** [modelscope/FunASR#1577]
直接跑demo测试时，语音中间说how are you时how可能会丢失，说happy new year时happy可能会丢失。基本上是形状的单词容易丢失。

**Comment by tramphero** [comment]
This likely pertains to the performance issue of the general Chinese speech recognition model when dealing with mixed Chinese-English speech. We will enhance the corresponding performance in subsequent model iterations.
