### ISSUE TITLE
生成标点包含、等时会出现字符长度与时间长度不相等

### ISSUE THREAD

**Issue by GioGioBond** [modelscope/FunASR#1606]
我的录音asr识别结果中str长度为7424，时间长度是6767，其中标点有[？，。.、]五种共652个，长度还是差5个，统计了一下顿号刚好出现五次，这是正常的吗，给的测试音频倒是长度匹配。

**Comment by lyblsgo** [comment]
Please describe your problem in detail.

**Comment by lyblsgo** [comment]
Let's close this issue for now. If needed, reopen it.
