### ISSUE TITLE
Vad模型处理数据会一直卡住

### ISSUE THREAD

**Issue by CNXiDaDa** [modelscope/FunASR#1643]
What is your question?
    我用进程方式启动AutoModel处理，16K单声道的wav音频数据，vad模型内部处理数据直接卡住不动，请大佬帮我看看进程启动下vad模型内部处理数据为什么会卡住。
    funasr->utils->load_utils.py的64行 data_or_path_or_list = data_or_path_or_list.mean(0)

    ps：用线程模式就能正常执行，但咱们线程模式长时间运行，有严重的内存泄漏，而且vad不支持多线程。
  

Code
.....
pool = multiprocessing.Pool(2)
pool.apply(func=convert, args=(wavepath))

.....
def convert(wavepath):
    model = AutoModel(model="iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
                      model_revision="v2.0.4",
                      vad_model="iic/speech_fsmn_vad_zh-cn-16k-common-pytorch",
                      vad_model_revision="v2.0.4",
                      punc_model="iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch",
                      punc_model_revision="v2.0.4",
                      spk_model="iic/speech_campplus_sv_zh-cn_16k-common",
                      spk_model_revision="v2.0.2",
                      ncpu=1,
                      device="cpu",
                      disable_pbar=True,
                      disable_log=False
                      )

     model.generate(input=wavepath)
)
What have you tried?
In a pytorch docker container, run pip install funasr and then the script above.

What's your environment?
OS (e.g., Linux):
FunASR Version (e.g., 1.0.0): 1.0.19
ModelScope Version (e.g., 1.11.0): None (do not need it)
PyTorch Version (e.g., 2.0.0): 2.2.2
How you installed funasr (pip, source): pip
Python version: 3.10.14
GPU (e.g., V100M32): NVIDIA GeForce RTX 4090
CUDA/cuDNN version (e.g., cuda11.7): cuda11.8
Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1): pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime
Any other relevant information:

**Comment by I-am-your-grandfather** [comment]
@LauraGPT

**Comment by jinqinn** [comment]
我现在不是卡住，而是在子进程中加载模型的时候报错：TypeError: 'NoneType' object is not callable

**Comment by semicarryispig** [comment]
你好，这个问题解决了吗？

**Comment by MENGHAH** [comment]
你好，请问内存泄漏问题解决了吗
