### ISSUE TITLE
英文batch推理的错误比单个推理多很多

### ISSUE THREAD

**Issue by wincing2** [modelscope/FunASR#1648]
英文模型用的是paraformer-eng，使用AutoModel进行batch推理和单条推理。经测听，batch推理的结果错的更多，都是少字。
中文模型（speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch）的batch推理则正常，虽然与单条推理的结果也有差异，但两者的错误率差不多。

**Comment by Wkdwlaud** [comment]
想问一下batch推理是指定初始化AutoModel时的batch_size就可以吗？您那边设置的是多少呢？
input可以传入list吗？
