### ISSUE TITLE
语音中4个字，经常识别丢失了最后一个字，麻烦看下

### ISSUE THREAD

**Issue by yk3372** [modelscope/FunASR#1683]
## ❓ Questions and Help
我们在语音识别 中，发现经常会丢失最后一个字，这里提供一个测试的demo，麻烦帮忙看下：

环境：Linux ubuntu

在终端运行命令：
`funasr ++model="paraformer-zh"  ++input=aaaa.wav`

拿到的结果是：
[{'key': 'rand_key_2yW4Acq9GFz6Y', 'text': '我 要 打', 'timestamp': [[1830, 2050], [2050, 2270], [2270, 3175]]}]

实际上期待的文字是： 我要打卡，丢失了最后的“卡”字

测试音频见附件，解压后即可使用

麻烦大佬帮忙看下~

**Comment by yk3372** [comment]
[aaaa.wav.zip](https://github.com/alibaba-damo-academy/FunASR/files/15158739/aaaa.wav.zip)

**Comment by xingchensong** [comment]
可以尝试用这里的方法finetune一下 https://arxiv.org/abs/2211.00522  专门用来解决这种尾部缺失问题的

**Comment by yk3372** [comment]
> 可以尝试用这里的方法finetune一下 https://arxiv.org/abs/2211.00522 专门用来解决这种尾部缺失问题的

好的我试一下，多谢

**Comment by ChEnYoNgB** [comment]
> > 可以尝试用这里的方法finetune一下 https://arxiv.org/abs/2211.00522 专门用来解决这种尾部缺失问题的
> 
> 好的我试一下，多谢

你好请问这个方法具体应该怎么做呢，对非实时的有效果吗
