### ISSUE TITLE
offline results 少了开头的一个字

### ISSUE THREAD

**Issue by Skypow2012** [modelscope/FunASR#1699]
![Snipaste_2024-05-08_00-21-24](https://github.com/alibaba-damo-academy/FunASR/assets/18132118/1c545bda-e094-41ec-b7c0-bf4a3a4d7267)
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

offline results 少了开头的一个字

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_online_zh.md
参考这里启动的服务

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by lyblsgo** [comment]
I am unable to replicate your issue on my side. If the problem still exists, please provide a test audio file.

**Comment by lyblsgo** [comment]
Let's close this issue for now. If needed, reopen it.
