### ISSUE TITLE
When running paraformer, an error occurs in the first step of extracting cmvn features.

### ISSUE THREAD

**Issue by didi222-lqq** [modelscope/FunASR#1744]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/84363031/b27bd3d7-a6f4-41de-bacf-3dc186cd6338)
torch 2.2.0
cuda 11.8
torchaudio 2.2.0
torchvision 0.17.0

**Comment by LauraGPT** [comment]
You could solve it by google.
