### ISSUE TITLE
ValueError: invalid character: @

### ISSUE THREAD

**Issue by WjMessi1** [modelscope/FunASR#1761]
个人制作的数据集内，会把邮箱中的地址@写入到 label 中，但是@好像是个特殊字符，因此训练出的模型，在用python进行模型推理的结果中包含@时，会有报错

## 🐛 Bug

报错内容如下：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87363191/7cc82b4e-afc1-4ca3-b0c0-dceb70d6b9ef)

### Expected behavior
修改成这样后，就不会报错了，但是损失了识别结果@字符

![image](https://github.com/alibaba-damo-academy/FunASR/assets/87363191/1040d9bd-0062-4b72-b5ee-675dda4ce5e1)

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.25):

**Comment by LauraGPT** [comment]
Please replace the @ with `at` or `艾特` in training data. `@` is specical token to concat subword.
