### ISSUE TITLE
docker运行使用ssl失败，访问wss://127.0.0.1:10095/不行，ws可以

### ISSUE THREAD

**Issue by zhouganglong** [modelscope/FunASR#1762]
ssl证书我已经在阿里云申请了免费3个月的证书，下载出是voice.xelp.cn.key、voice.xelp.cn_chain.crt、voice.xelp.cn_public.crt这三个，我就替换了docker里的runtime/ssl_key/server.crt和runtime/ssl_key/server.key这2个文件的密钥，但最后运行失败，打开log.txt日志报这个错`I20240528 15:17:12.388139  2248 websocket-server-2pass.cpp:29] on_tls_init called with hdl: 0x7fa28c010af0
I20240528 15:17:12.388193  2248 websocket-server-2pass.cpp:30] using TLS mode: Mozilla Intermediate
[2024-05-28 15:17:12] [error] handle_transport_init received error: TLS handshake failed
[2024-05-28 15:17:12] [info] asio async_shutdown error: asio.ssl:336462231 (shutdown while in init (SSL routines, SSL_shutdown))`

不知道哪里我问题，想部署在服务器上，但是浏览器限制必须wss就去申请了，可是一直不行

**Comment by lyblsgo** [comment]
自带的证书不可以用吗？
log确认下服务端是否成功加载证书

**Comment by zhouganglong** [comment]
I20240528 16:16:19.500327    92 funasr-wss-server-2pass.cpp:539] SSL is opened!
certfile path is /workspace/FunASR/runtime/ssl_key/server.crt
I20240528 16:16:19.500384    92 websocket-server-2pass.cpp:29] on_tls_init called with hdl: 0x55ba4e6cbed0 
I20240528 16:16:19.500388    92 websocket-server-2pass.cpp:30] using TLS mode: Mozilla Intermediate 是已经加载成功的，现在用自带还是我换过一个证书都不行

**Comment by lyblsgo** [comment]
Let's close this issue for now. If needed, reopen it.
