### ISSUE TITLE
How to create audio profiles for speakers for re-identification?

### ISSUE THREAD

**Issue by hmehdi515** [modelscope/FunASR#1766]
## ❓ Questions and Help
Any way to create voice profiles?

#### What is your question?
Is there a way to store and re-identify voice profiles (similar to BOT-Sort for classifying and re-identifying images) by extracting embeddings that characterize the speaker's voice?
Example: 
Give model an audio file with containing multiple voices and use speech diarization for segmentation. 
Store the embeddings in a structure database for future comparison and re-identification. 
Compare new embeddings against stored ones to identify if a speaker has been previously encountered.

#### What's your environment?

 - OS (e.g., Linux): Windows
 - FunASR Version (e.g., 1.0.0): 1.0.5

**Comment by goodpeter-sun** [comment]
How was this topic solved? Where to find the solution?

**Comment by hmehdi515** [comment]
I did not use this repo directly, but you can use embedding models like https://huggingface.co/pyannote/embedding to embed audio spoken by the target speaker, then average out those embeddings and store them for future comparison via clustering / cosine similarity.

Hope this helps!
