### ISSUE TITLE
尝试使用 finetune.sh 微调 seaco-paraformer ,微调后发现，每个epoch 的model.pt增大了很大，从原模型的800多M，增大到了2.44GB多，这是什么原因

### ISSUE THREAD

**Issue by locasxe** [modelscope/FunASR#1774]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

尝试使用 finetune.sh 微调 seaco-paraformer ,微调后发现，每个epoch 的model.pt增大了很大，从原模型的800多M，增大到了2.44GB多，这是什么原因

### To Reproduce

bash finetune.sh

### Expected behavior

模型大小应保持一致

### Environment

 - OS (e.g., Linux):
 - FunASR Version 最新:
 - PyTorch Version 2.0.0:
 - How you installed funasr source:
 - Python version : 3.9
 - CUDA/cuDNN version cuda12.0:

**Comment by zihaozhu93** [comment]
请问这个问题修复了吗？使用最新的代码在finetune contextual_paraformer时也碰到同样的问题.
<img width="394" alt="image" src="https://github.com/modelscope/FunASR/assets/20263795/39c15b28-8f60-4c51-b31f-d3aee2ae4573">，不过看到有一个model.pt.avg10 大小和原模型大小差不多？所以是应该用这个去推理吗？另外，按照文档
`_如果，您希望部署您finetune后的模型（例如10epoch.pb），需要手动将模型重命名为model.pb，并将原modelscope中模型model.pb替换掉，将路径指定为model_dir即可。_`，替换，docker内runserver时指定本地model_dir，后提示报错，

` model is not exist, begin to export /xxpath/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404/model_blade.torchscript
E20240710 03:09:23.102286   477 funasr-wss-server.cpp:301] /xxpath/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404/model_blade.torchscript do not exists.
`，这个是哪里操作不当吗

**Comment by asyncat** [comment]
@locasxe 遇到相同的问题，请问您是怎么解决的？

**Comment by 123wimin321** [comment]
您好，想问下是怎么解决的呢？是什么原因呢？

**Comment by locasxe** [comment]
这个问题是模型保存方式引起，详情可以看average_checkpoints这个函数 @123wimin321 @asyncat
