### ISSUE TITLE
如何在funasr-runtime-sdk-cpu-0.4.4 websocket服务端上开启说话人识别？

### ISSUE THREAD

**Issue by hooploop** [modelscope/FunASR#1780]
如何在funasr-runtime-sdk-cpu-0.4.4 websocket服务端上开启说话人识别？

根据下面的文档开启了中文离线识别的wss server端
https://github.com/modelscope/FunASR/blob/main/runtime/quick_start_zh.md

有没有办法开启说话人识别呢？
目前了解到，下面的python server的spk_model字段支持说话人模型
https://github.com/modelscope/FunASR/blob/99ecaca8695fc482fd351c1619e3f9ebb274af93/examples/README_zh.md

![image](https://github.com/modelscope/FunASR/assets/97428008/7d21fa32-2cd6-465f-872f-8b07f4ffe75a)

**Comment by lyblsgo** [comment]
服务部署目前不支持 说话人识别模型

**Comment by zzk2021** [comment]
你好，如果我要实现流式说话人识别，这个做流式聚类可以吗？
