### ISSUE TITLE
funasr音频问题

### ISSUE THREAD

**Issue by 851543** [modelscope/FunASR#1781]
我前端的音频数据代码如下：
    
    //实时语音识别功能
    // 获取音频文件结束
    // 初始化麦克风
    recOpen() {
      const _this = this
      let audioBlob = new Blob()
      // 录音对象
      var Recorder = function (stream) {
        var sampleBits = 16 // 输出采样数位 8, 16
        var sampleRate = 16000 // 输出采样率
        var context = new AudioContext()
        var audioInput = context.createMediaStreamSource(stream)
        var recorder = context.createScriptProcessor(4096, 1, 1)
        var audioData = {
          size: 0, // 录音文件长度
          buffer: [], // 录音缓存
          inputSampleRate: 48000, // 输入采样率
          inputSampleBits: 16, // 输入采样数位 8, 16
          outputSampleRate: sampleRate, // 输出采样数位
          oututSampleBits: sampleBits, // 输出采样率
          clear: function () {
            this.buffer = []
            this.size = 0
          },
          input: function (data) {
            this.buffer.push(new Float32Array(data))
            this.size += data.length
          },
          compress: function () {
            // 合并压缩
            var data = new Float32Array(this.size)
            var offset = 0
            for (var i = 0; i < this.buffer.length; i++) {
              data.set(this.buffer[i], offset)
              offset += this.buffer[i].length
            }
            // 压缩
            var compression = parseInt(this.inputSampleRate / this.outputSampleRate) // 计算采样率压缩比例
            var length = data.length / compression // 计算压缩后的数据长度
            var result = new Float32Array(length) // 创建一个新的浮点型数组来存储结果
            let index = 0
            let j = 0

            // 循环，将原始数据按照压缩比例填充到结果数组中
            while (index < length) {
              result[index] = data[j] // 将原始数据的值存储到结果数组中
              j += compression // 增加原始数据索引以跳过一些数据
              index++ // 增加结果数组索引
            }

            return result // 返回压缩后的数据结果
          },
          encodePCM: function () {
            var sampleBits = Math.min(this.inputSampleBits, this.oututSampleBits)
            var bytes = this.compress()
            var dataLength = bytes.length * (sampleBits / 8)
            var buffer = new ArrayBuffer(dataLength)
            var data = new DataView(buffer)
            var offset = 0
            for (var i = 0; i < bytes.length; i++, offset += 2) {
              var s = Math.max(-1, Math.min(1, bytes[i]))
              data.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7fff, true)
            }
            // return data
            return new Blob([data], { type: 'audio/wav' })
          },
        }
        var sendData = function () {
          // 对以获取的数据进行处理(分包)
          var reader = new FileReader()
          const blob = audioData.encodePCM()
          reader.readAsArrayBuffer(blob)
          reader.onloadend = function () {
            var binary = reader.result
            var array = new Uint8Array(binary)
            _this.bol = array.every((item) => {
              return item === 0
            })
            if (_this.ws === null) {
              // recorder.disconnect()
            } else {
              if (_this.bol) {
                _this.finishConfirm()
              }
              _this.ws.send(binary)
              if (_this.cansendaudio === false) {
                console.log('false一次')
                _this.setSpeakerId(_this.selectedValue)
                _this.cansendaudio = true
              }
            }
          }
          audioData.clear() // 每次发送完成则清理掉旧数据
        }
        this.start = function () {
          audioInput.connect(recorder)
          recorder.connect(context.destination)
        }
        this.stop = function () {
          recorder.disconnect()
          console.log('disconnect断开连接')
        }
        this.getBlob = function () {
          return audioData.encodePCM()
        }
        this.clear = function () {
          audioData.clear()
        }
        this.getaudio = function () {
          audioData.getFullWavData()
        }
        recorder.onaudioprocess = function (e) {
          var inputBuffer = e.inputBuffer.getChannelData(0)
          audioData.input(inputBuffer)
          if (_this.isStop === true) {
            audioData.clear()
          } else {
            sendData()
          }
        }
      }
      navigator.getUserMedia(
        {
          audio: true,
        },
        (mediaStream) => {
          this.initRecorder(new Recorder(mediaStream))
        },
        (error) => {
          switch (error.message || error.name) {
            case 'PERMISSION_DENIED':
            case 'PermissionDeniedError':
              this.$message.error('用户拒绝提供信息')
              break
            case 'NOT_SUPPORTED_ERROR':
            case 'NotSupportedError':
              this.$message.error('浏览器不支持硬件设备')
              break
            case 'MANDATORY_UNSATISFIED_ERROR':
            case 'MandatoryUnsatisfiedError':
              this.$message.error('无法发现指定的硬件设备')
              break
            default:
              this.$message.error('无法打开麦克风')
              break
          }
        }
      )
    }

传参为 ：mode: '2pass',
                wav_name: 'h5',
                is_speaking: true,
                chunk_size: [5, 10, 5],
                hotwords: { 阿里巴巴: 20, 通义实验室: 30 },
                itn: false,
                chunk_interval: 10,

服务采用funas源码funasr_wss_server.py 
问题：语音实时识别根本用不了，一句话半天不返回，返回还是错误的识别。

**Comment by LauraGPT** [comment]
funasr_wss_server.py only support bytes:

16000 sampling rate
single channel

But we suggest you to use the docker by: www.funasr.com
