### ISSUE TITLE
我通过docker容器化部署了FunASR，但是在通过网页连接时却提示连接失败

### ISSUE THREAD

**Issue by weiba111** [modelscope/FunASR#1799]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
我在一台虚拟机上通过docker容器化部署了FunASR服务，关闭了虚拟机的防火墙，在FunASR的日志中也提示了初始化成功，但是当我在html页面上通过webscoket连接时，却提示我连接失败，请问可能是什么原因
![image](https://github.com/modelscope/FunASR/assets/149772631/74534ecd-8d79-4db8-8eee-04c644b6362f)
这是我的docker容器信息
![image](https://github.com/modelscope/FunASR/assets/149772631/a4bb5742-f37c-4376-a77b-f89bca6db505)
我的docker是自己安装的，因为在运行文档地址给出的安装脚本时安装失败，所以是自己安装的dockerhttps://github.com/modelscope/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
点击授权

**Comment by weiba111** [comment]
> 点击授权

什么意思？有点没太明白

**Comment by LauraGPT** [comment]
> > 点击授权
> 
> 什么意思？有点没太明白

页面上有一个授权
