### ISSUE TITLE
Mac M2 Max 源码运行如何调用gpu

### ISSUE THREAD

**Issue by Oceannew** [modelscope/FunASR#1802]
我修改了funasr_wss_server.py文件的配置，把cpu改为mps并没有效果。

我在google上没有找到解决方法。

修改的代码：

parser.add_argument("--ngpu", type=int, default=1, help="0 for cpu, 1 for gpu")
parser.add_argument("--device", type=str, default="mps", help="cuda, cpu")
parser.add_argument("--ncpu", type=int, default=10, help="cpu cores")

environment：

 - OS (e.g., Linux):**MAC**
 - FunASR Version (e.g., 1.0.0):**1.0.18**
 - ModelScope Version (e.g., 1.11.0):**1.14.0**
 - PyTorch Version (e.g., 2.0.0):**2.3.0**
 - How you installed funasr (`pip`, source):**source**
 - Python version:**3.8.0**
 - GPU (e.g., V100M32):**M2**
 - CUDA/cuDNN version (e.g., cuda11.7):**none**
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
We don't know `M2`, you could ref to torch. funasr is torch-based.

**Comment by AlienKevin** [comment]
I can confirm that SenseVoiceSmall is runnable on mps, after commenting out the lines that coerse the device to CPU.
@LauraGPT Could you please remove the device coersion lines? I was extremely confused at first because I specified the device as MPS but saw no GPU usage on my Mac. If you are worried about device compatability for certain model-device pairs, maybe a warning message is more appropriate/helpful.

**Comment by LauraGPT** [comment]
> I can confirm that SenseVoiceSmall is runnable on mps, after commenting out the lines that coerse the device to CPU. @LauraGPT Could you please remove the device coersion lines? I was extremely confused at first because I specified the device as MPS but saw no GPU usage on my Mac. If you are worried about device compatability for certain model-device pairs, maybe a warning message is more appropriate/helpful.

Fine. Don you know how to detect running on mps?

**Comment by AlienKevin** [comment]
@LauraGPT You can use `torch.backends.mps.is_available()` to detect if the MPS backend is supported. And the device name for MPS is simply the string `mps`.

**Comment by thorory** [comment]
@AlienKevin J
Comment out the following lines, and set the device to 'mps'. After this change, the speed in stream mode can be increased from 5 it/s to 12 it/s when tested.

`def build_model(**kwargs):
        assert "model" in kwargs
        if "model_conf" not in kwargs:
            logging.info("download models from model hub: {}".format(kwargs.get("hub", "ms")))
            kwargs = download_model(**kwargs)

        set_all_random_seed(kwargs.get("seed", 0))

        device = kwargs.get("device", "cuda")
        # comment these 3 lines
        # if not torch.cuda.is_available() or kwargs.get("ngpu", 1) == 0:
        #    device = "cpu"
        #    kwargs["batch_size"] = 1
        kwargs["device"] = device

        torch.set_num_threads(kwargs.get("ncpu", 4))`
