### ISSUE TITLE
离线模型和在线模型有什么区别，cache里面有什么内容是在线模型需要缓存的。

### ISSUE THREAD

**Issue by lidingke** [modelscope/FunASR#1824]
1. runtime/python/onnxruntime/demo_vad_online.py中vad模型的调用每次都需要传个in_cache进去，如果我要将vad模型封装成一个http的接口，这样就需要知道每次调用这个接口缓存了哪些状态。
2. 如果我不用online模型，只用offline模型，vad和模型的online版本会有哪些效果上的差异吗？
3. 同样的问题paraformer的online模型也有。

**Comment by Ignalxy** [comment]
服务端保存对应会话的cache就可以了
