### ISSUE TITLE
seaco-paraformer训练时seaco标签问题

### ISSUE THREAD

**Issue by ALIVE321** [modelscope/FunASR#1829]
## ❓ Questions and Help
https://github.com/modelscope/FunASR/blob/45d7aa9004763684fb748ee17942ecba81042201/funasr/datasets/audio_datasets/datasets.py#L231-L250

你好，我看到这里构建标签时，每个样本只匹配了自身生成的热词，不应该匹配所有的热词吗？

**Comment by R1ckShi** [comment]
在一个batch里面有可能出现来自句子a的热词在句子b中出现的情况，但是概率较低
这里为了计算效率，假设没有这种情况的出现了

**Comment by ALIVE321** [comment]
thx 不过在我用的数据上热词重叠会比较严重，看来得自己做下修改

**Comment by R1ckShi** [comment]
欢迎pr一下: )
