### ISSUE TITLE
funasr是否能将直播流中的音频转录为文字

### ISSUE THREAD

**Issue by dedebao** [modelscope/FunASR#1830]
对于现在常见的直播流，比如http协议，rtmp协议，rtsp协议拉到的直播流，funasr能否实时将直播流中音频转录为文字？如果可以的话，请给个示例参考一下

**Comment by LauraGPT** [comment]
We have websocket, please ref to: www.funasr.com

**Comment by dedebao** [comment]
我看到websocket的demo了，里面要么选一个本地文件，要么在web页面上选择麦克风，可我的问题是，假设拿到的是一个rtsp的直播流地址，如何接入funasr实时将直播中的音频解说转换为文字




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "modelscope/FunASR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月20日(星期四) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [modelscope/FunASR] funasr是否能将直播流中的音频转录为文字 (Issue #1830)





 
We have websocket, please ref to: www.funasr.com
