### ISSUE TITLE
IndexError: index 6802 is out of bounds for dimension 0 with size 6802

### ISSUE THREAD

**Issue by lichengyang666** [modelscope/FunASR#1832]
#### What is your question?
本地运行离线asr服务，一开始正常识别，运行一段时间后报错，原来可以识别的音频现在也开始报错

#### Code
from funasr import AutoModel
![image](https://github.com/modelscope/FunASR/assets/47627452/273a83ec-2ebe-4f36-a05b-28fa6d130bc5)
![image](https://github.com/modelscope/FunASR/assets/47627452/dd688666-8b57-43ef-9997-b40f8d9dab94)

#### What have you tried?
开始正常，识别了若干个离线录音之后开始报错了，还提示“Something wrong with the VAD algorithm”

#### What's your environment?

 - OS (e.g., Linux): window（linux下面也有类似错误）
 - FunASR Version (e.g., 1.0.0): 1.0.27
 - ModelScope Version (e.g., 1.11.0):  1.13.3
 - PyTorch Version (e.g., 2.0.0): 2.1.0
 - How you installed funasr (`pip`, source): pip 清华源
 - Python version: 3.8
 - GPU (e.g., V100M32) CPU
 - CUDA/cuDNN version (e.g., cuda11.7):  CPU
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1) 未使用
 - Any other relevant information:

**Comment by LauraGPT** [comment]
set `cache={}` when decode

**Comment by di-osc** [comment]
> set `cache={}` when decode

能否给个推理的代码示例

**Comment by LauraGPT** [comment]
> > set `cache={}` when decode
> 
> 能否给个推理的代码示例

```python
res = model.generate(
    input=input_file,
    cache={},)
```

**Comment by lichengyang666** [comment]
> > > set `cache={}` when decode
> > 
> > 
> > 能否给个推理的代码示例
> 
> ```python
> res = model.generate(
>     input=input_file,
>     cache={},)
> ```

大佬 试了不行呀 还是会出现同样的错误

**Comment by YouTwoMeToo** [comment]
> > > > set `cache={}` when decode
> > > 
> > > 
> > > 能否给个推理的代码示例
> > 
> > 
> > res = model.generate(
> >     input=input_file,
> >     cache={},)
> 
> 大佬 试了不行呀 还是会出现同样的错误

请问解决了吗，我加了之后有所好转，目前没有出现问题了
