### ISSUE TITLE
说话人分割，用新闻联播音频，男女主持人的“晚上好”无法区分成两个人

### ISSUE THREAD

**Issue by wuhongsheng** [modelscope/FunASR#1853]
![image](https://github.com/modelscope/FunASR/assets/10295461/6a0307b7-24f3-4930-8d54-e940a00a52c7)

**Comment by xxxzsgxxx** [comment]
看看你用的模型呗？


> ![image](https://private-user-images.githubusercontent.com/10295461/343690899-6a0307b7-24f3-4930-8d54-e940a00a52c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjU1NDcsIm5iZiI6MTcxOTU2NTI0NywicGF0aCI6Ii8xMDI5NTQ2MS8zNDM2OTA4OTktNmEwMzA3YjctMjRmMy00OTMwLThkNTQtZTk0MGEwMGE1MmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA5MDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMTgzM2MyM2UyYWFmZjM2Y2IxYjE2ZjlhMGE1NGM3MDhkNjc4MWIzOWJkM2IyMzZiNGM1NGM5ZTU4MzU0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HXWqExjhf4hPetPkpov1kC0knsPfTQCuLArl1wBuM74)

**Comment by java668** [comment]
怎么知道 SPEAKER_0 和 SPEAKER_2 那个是男的那个是女的？

**Comment by wuhongsheng** [comment]
找到原因了，CAM++说话人识别有个合并短句speakid 把这个阈值调小点可以规避
![image](https://github.com/modelscope/FunASR/assets/10295461/17e15339-dd5c-45c5-af48-89b15b9b0147)
