### ISSUE TITLE
speaker id 不是递增的

### ISSUE THREAD

**Issue by wuhongsheng** [modelscope/FunASR#1854]
![image](https://github.com/modelscope/FunASR/assets/10295461/b9a52e51-7c12-416a-8bf3-743bc5b3d31f)

**Comment by wuhongsheng** [comment]
[https://github.com/modelscope/FunASR/pull/1870](url)

**Comment by tangweihui** [comment]
可以问下你这个是哪个模型跑出来的么？这个数据结果是我需要的，没找到合适的模型
