### ISSUE TITLE
docker安装后,本地调用asr服务连不上.

### ISSUE THREAD

**Issue by V-yw** [modelscope/FunASR#1868]
本地根据官网文档docker run 起来之后,跑了脚本.
```
bash run_server.sh   --download-model-dir /workspace/models   --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx   --model-dir damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch    --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx   --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst   --itn-dir thuduj12/fst_itn_zh   --hotword /workspace/models/hotwords.txt  --certfile 0
```
![image](https://github.com/modelscope/FunASR/assets/16344112/8d2511ac-2d09-40d8-85e9-81e9953c3cae)

但是我本级打开使用html client 连接asr server 显示连接不上. telnet 10098 是可以的.
97d711252363   registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-gpu-0.1.1   "bash"                   2 hours ago   Up About an hour   0.0.0.0:10098->10095/tcp, :::10098->10095/tcp   nervous_euclid

![image](https://github.com/modelscope/FunASR/assets/16344112/f7bdac01-70c2-47d3-8250-be0aa1e38ab0)

但是web ui client 输入 wss://192.168.6.26:10098/ 或者ws 或者http 都失败.
![image](https://github.com/modelscope/FunASR/assets/16344112/ff953c06-dbe8-41be-a7e2-ca916c125cf4)

**Comment by lyblsgo** [comment]
服务端和客户端都打开ssl

**Comment by MrRohwei** [comment]
点一下下面的手工授权

**Comment by MrRohwei** [comment]
我大概知道了，我这边启动也有这个问题，里面的模型下载失败了。
![image](https://github.com/user-attachments/assets/9aa30d57-aa68-48eb-93f4-0278ccdcff94)

**Comment by lyblsgo** [comment]
Let's close this issue for now. If needed, reopen it.
