### ISSUE TITLE
whisper输入中文音频，但是输出的识别结果全是英文

### ISSUE THREAD

**Issue by Shi-Yuhong** [modelscope/FunASR#1881]
我访问了whisper modelscope的网页，并尝试运行给出的示例代码
`from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='iic/Whisper-large-v3', model_revision="v2.0.5")

rec_result = inference_pipeline(input='https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav', language=None)
print(rec_result)`
**已知输入的音频是中文音频，但是输出的识别结果是英文**
[{'key': 'asr_example_zh', 'text': 'Welcome to the demo of the voice recognition model launched by the Darmok University.'}]
尝试替换成其他中文音频，结果也是一样的，输出结果是英文
请问是哪里我设置错了吗，或者我如何解决以上问题呢

**Comment by LauraGPT** [comment]
https://github.com/modelscope/FunASR/blob/main/examples/industrial_data_pretraining/whisper/demo.py

**Comment by Shi-Yuhong** [comment]
> https://github.com/modelscope/FunASR/blob/main/examples/industrial_data_pretraining/whisper/demo.py

似乎仍然不可以：
2024-07-04 23:53:10,181 - modelscope - INFO - Use user-specified model revision: master
rtf_avg: 0.026: 100%|█████████████████████████████████| 1/1 [00:00<00:00,  6.83it/s]
rtf_avg: 0.318: 100%|█████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]
rtf_avg: 0.284, time_speech:  5.547, time_escape: 1.576: 100%|█| 1/1 [00:01<00:00,  
[{'key': 'asr_example_zh', 'text': 'Welcome to experience the sound recognition model launched by Damoyuan.'}]
