### ISSUE TITLE
用不同的funasr版本，使用相同whisper模型跑出来的结果不一致

### ISSUE THREAD

**Issue by AITDASR** [modelscope/FunASR#1890]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

测试代码：
````
from funasr import AutoModel
model = AutoModel(model="/home/ubuntu/workspace/voice_server/models/Whisper-large-v3/",
model_revision='v2.0.4',device='cuda:0',)
res = model.generate(input="/home/ubuntu/workspace/voice_server/data/dialog-test.wav", 
                     language='zh', task='transcribe')
print(res)
````
使用funasr==1.0.27 解码为中文，使用1.0.28版本及以上，解码为英文
模型：https://modelscope.cn/models/iic/Whisper-large-v3，下载到本地后使用

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0): 1.0.28
 - ModelScope Version (e.g., 1.11.0): 1.16.0
 - PyTorch Version (e.g., 2.0.0): 2.3.1
 - How you installed funasr (`pip`, source): pip
 - Python version: 3.10.12
 - GPU (e.g., V100M32) A10
 - CUDA/cuDNN version (e.g., cuda11.7): cuda12.1
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Please update funasr-1.1.0, and ref to https://github.com/modelscope/FunASR/blob/main/examples/industrial_data_pretraining/whisper/demo.py

**Comment by AITDASR** [comment]
还是不行，我的音频内容是：“测试一下翻译功能，这是第一句，这是第二句，这是第三句，这是第四句，这是第五句，好的结束”，识别结果为：[{'key': 'dialog-test', 'text': 'Test the translation function. This is the first sentence. This is the second sentence This is the third sentence. This is the fourth sentence This is the fifth sentence. Ok, done'}]

**Comment by LauraGPT** [comment]
Please upload the wav file

**Comment by AITDASR** [comment]
> Please upload the wav file

https://huggingface.co/HalFTeen/sherpa-ncnn-hotwords-test/resolve/main/dialog-test.wav

**Comment by AITDASR** [comment]
version1.0.28 funasr/models/whisper/model.py line115: 
`result = whisper.decode(self.model, speech, language='english')`  
hardcode with language=‘english’  instead of passing by parameter

**Comment by LauraGPT** [comment]
In the latest version:

```python

from funasr import AutoModel

model = AutoModel(
    model="iic/Whisper-large-v3",
    vad_model="iic/speech_fsmn_vad_zh-cn-16k-common-pytorch",
    vad_kwargs={"max_single_segment_time": 30000},
)

DecodingOptions = {
    "task": "transcribe",
    "language": None,
    "beam_size": None,
    "fp16": True,
    "without_timestamps": False,
    "prompt": None,
}
res = model.generate(
    DecodingOptions=DecodingOptions,
    batch_size_s=0,
    input="https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav",
)

print(res)
```

**Comment by LauraGPT** [comment]
Bugfix: https://github.com/modelscope/FunASR/commit/7f6099140a781bd18115bd82a5dd0525d43af290
