### ISSUE TITLE
多次调用asr py出现Tensor Type Error

### ISSUE THREAD

**Issue by hyq-hub** [modelscope/FunASR#1894]
import os
import json
from funasr import AutoModel

model = AutoModel(model="paraformer-zh", vad_model="fsmn-vad", vad_kwargs={"max_single_segment_time": 60000},punc_model="ct-punc", spk_model="cam++", device = "cuda:0")

def transcribe_audio_param(audio_path):
    print("begin transcribe param")
    # 获取输出目录和文件名
    output_dir = os.path.dirname(audio_path)
    file_extension = os.path.splitext(audio_path)[1].lower()
    base_name = os.path.splitext(os.path.basename(audio_path))[0]
    output_file = os.path.join(output_dir, base_name + '_asr_param.json')
    # 检查输出文件是否已存在
    if os.path.exists(output_file):
        return output_file
    # 检查支持的文件类型
    if file_extension not in ['.wav', '.mp3']:
        print("Unsupported file type. Please use a .wav or .mp3 file.")
        return None
    # 初始化模型
    # 执行非实时语音识别
    result = model.generate(input=audio_path, batch_size_s=60)  # 调整批次大小为60秒

    # 保存结果到JSON文件
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(result[0], f, ensure_ascii=False, indent=4)

    return output_file
直接调用以上py进行asr可以正常运作，在sh脚本1中调用，进行多个文件asr也可以，但在脚本2多次调用脚本1 时，出现以下error，且一直无法解决，请问有无大佬了解相关情况或者有可能的解决方法呀？非常感谢！

![WechatIMG53](https://github.com/modelscope/FunASR/assets/143300392/5876955a-b1de-4773-8149-be956065ffba)

**Comment by LauraGPT** [comment]
Please check whether `wav` file exists or not.
