### ISSUE TITLE
请问paraformer训练时对数据有时长限制吗，我下了一个数据集，是20多个音频文件，时长都是几十分钟一个，训练之后测试得到的模型效果和训练前一样

### ISSUE THREAD

**Issue by Yoki185** [modelscope/FunASR#1896]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help
请问paraformer训练时对数据有时长限制吗，我使用的数据集，是20多个音频文件，时长都是几十分钟一个，训练之后测试得到的模型效果和训练前一样

### Before asking:
1. search the issues.
2. search the docs.

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by RERUIN76** [comment]
这个问题您似乎已经解决了，可以分享一下解决方法吗，我现在微调时也是训练后和训练前推理效果相同，ps:我只训练了五条5秒左右的数据。是否会是因为数据过少的原因。但是训练后的模型去推理训练时喂给的数据都不能正确识别。

**Comment by ChEnYoNgB** [comment]
> 这个问题您似乎已经解决了，可以分享一下解决方法吗，我现在微调时也是训练后和训练前推理效果相同，ps:我只训练了五条5秒左右的数据。是否会是因为数据过少的原因。但是训练后的模型去推理训练时喂给的数据都不能正确识别。

你好请问你解决了吗，微调至少需要多少数据呢
