### ISSUE TITLE
无网环境下部署报错

### ISSUE THREAD

**Issue by wuhongsheng** [modelscope/FunASR#1897]
<img width="1449" alt="image" src="https://github.com/modelscope/FunASR/assets/10295461/b11e81b7-3bc2-4e05-9e08-6e737b9dea14">

**Comment by qianbaidu1266** [comment]
同问，启动时为什么连接modelscope：
 /api/v1/models/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions (Caused by ReadTimeoutError("HTTPSConnectionPool(host='www.modelscope.cn', port=443): Read timed out.

**Comment by LauraGPT** [comment]
Set the `model ` to local path dir.
