### ISSUE TITLE
关于online模型导出onnx报错代码bug

### ISSUE THREAD

**Issue by fcs0329** [modelscope/FunASR#1905]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

File "/usr/local/lib/python3.8/dist-packages/funasr/utils/export_utils.py", line 59, in _onnx
    export_name = model.export_name + ".onnx"
TypeError: unsupported operand type(s) for +: 'method' and 'str'

### To Reproduce

使用脚本导出online模型时报错，使用脚本如下
`from funasr import AutoModel

model = AutoModel(
    model=("iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online")  
)

res = model.export(type="onnx", quantize=True)
print(res)`

#### Reason
/usr/local/lib/python3.8/dist-packages/funasr/models/paraformer_streaming/export_meta.py 代码bug，如下

> 
> import types
> 
> import torch
> from funasr.register import tables
> 
> def export_rebuild_model(model, **kwargs):
>     model.device = kwargs.get("device")
>     is_onnx = kwargs.get("type", "onnx") == "onnx"
>     encoder_class = tables.encoder_classes.get(kwargs["encoder"] + "Export")
>     model.encoder = encoder_class(model.encoder, onnx=is_onnx)
> 
>     predictor_class = tables.predictor_classes.get(kwargs["predictor"] + "Export")
>     model.predictor = predictor_class(model.predictor, onnx=is_onnx)
> 
>     decoder_class = tables.decoder_classes.get(kwargs["decoder"] + "Export")
>     model.decoder = decoder_class(model.decoder, onnx=is_onnx)
> 
>     from funasr.utils.torch_function import sequence_mask
> 
>     model.make_pad_mask = sequence_mask(kwargs["max_seq_len"], flip=False)
> 
>     model.forward = types.MethodType(export_forward, model)
>     model.export_dummy_inputs = types.MethodType(export_dummy_inputs, model)
>     model.export_input_names = types.MethodType(export_input_names, model)
>     model.export_output_names = types.MethodType(export_output_names, model)
>     model.export_dynamic_axes = types.MethodType(export_dynamic_axes, model)
>     model.export_name = types.MethodType(export_name, model)
> 
>     return model
> 
> def export_rebuild_model(model, **kwargs):
>     # self.device = kwargs.get("device")
>     is_onnx = kwargs.get("type", "onnx") == "onnx"
>     encoder_class = tables.encoder_classes.get(kwargs["encoder"] + "Export")
>     model.encoder = encoder_class(model.encoder, onnx=is_onnx)
> 
>     predictor_class = tables.predictor_classes.get(kwargs["predictor"] + "Export")
>     model.predictor = predictor_class(model.predictor, onnx=is_onnx)
> 
>     if kwargs["decoder"] == "ParaformerSANMDecoder":
>         kwargs["decoder"] = "ParaformerSANMDecoderOnline"
>     decoder_class = tables.decoder_classes.get(kwargs["decoder"] + "Export")
>     model.decoder = decoder_class(model.decoder, onnx=is_onnx)
> 
>     from funasr.utils.torch_function import sequence_mask
> 
>     model.make_pad_mask = sequence_mask(max_seq_len=None, flip=False)
> 
>     import copy
>     import types
> 
>     encoder_model = copy.copy(model)
>     decoder_model = copy.copy(model.decoder)
> 
>     # encoder
>     encoder_model.forward = types.MethodType(export_encoder_forward, encoder_model)
>     encoder_model.export_dummy_inputs = types.MethodType(export_encoder_dummy_inputs, encoder_model)
>     encoder_model.export_input_names = types.MethodType(export_encoder_input_names, encoder_model)
>     encoder_model.export_output_names = types.MethodType(export_encoder_output_names, encoder_model)
>     encoder_model.export_dynamic_axes = types.MethodType(export_encoder_dynamic_axes, encoder_model)
>     encoder_model.export_name = types.MethodType(export_encoder_name, encoder_model)
> 
>     # decoder
>     decoder_model.forward = types.MethodType(export_decoder_forward, decoder_model)
>     decoder_model.export_dummy_inputs = types.MethodType(export_decoder_dummy_inputs, decoder_model)
>     decoder_model.export_input_names = types.MethodType(export_decoder_input_names, decoder_model)
>     decoder_model.export_output_names = types.MethodType(export_decoder_output_names, decoder_model)
>     decoder_model.export_dynamic_axes = types.MethodType(export_decoder_dynamic_axes, decoder_model)
>     decoder_model.export_name = types.MethodType(export_decoder_name, decoder_model)
> 
>     return encoder_model, decoder_model
> 
> 
> 
### Debug

首先是重复定义了两次export_rebuild_model函数，可以对第一个函数进行注释或删除，其次缺少  encoder_model.export_name 与decoder_model.export_name
debug后代码如下

> 
> import types
> import torch
> from funasr.register import tables
> 
> def export_rebuild_model(model, **kwargs):
>     # self.device = kwargs.get("device")
>     is_onnx = kwargs.get("type", "onnx") == "onnx"
> 
>     encoder_class = tables.encoder_classes.get(kwargs["encoder"] + "Export")
>     model.encoder = encoder_class(model.encoder, onnx=is_onnx)
> 
>     predictor_class = tables.predictor_classes.get(kwargs["predictor"] + "Export")
>     model.predictor = predictor_class(model.predictor, onnx=is_onnx)
> 
>     if kwargs["decoder"] == "ParaformerSANMDecoder":
>         kwargs["decoder"] = "ParaformerSANMDecoderOnline"
>     decoder_class = tables.decoder_classes.get(kwargs["decoder"] + "Export")
>     model.decoder = decoder_class(model.decoder, onnx=is_onnx)
> 
>     from funasr.utils.torch_function import sequence_mask
> 
>     model.make_pad_mask = sequence_mask(max_seq_len=None, flip=False)
> 
>     import copy
>     import types
> 
>     encoder_model = copy.copy(model)
>     decoder_model = copy.copy(model.decoder)
> 
>     # encoder
>     encoder_model.forward = types.MethodType(export_encoder_forward, encoder_model)
>     encoder_model.export_dummy_inputs = types.MethodType(export_encoder_dummy_inputs, encoder_model)
>     encoder_model.export_input_names = types.MethodType(export_encoder_input_names, encoder_model)
>     encoder_model.export_output_names = types.MethodType(export_encoder_output_names, encoder_model)
>     encoder_model.export_dynamic_axes = types.MethodType(export_encoder_dynamic_axes, encoder_model)
>     encoder_model.export_name = types.MethodType(export_encoder_name, encoder_model)
> 
>     # decoder
>     decoder_model.forward = types.MethodType(export_decoder_forward, decoder_model)
>     decoder_model.export_dummy_inputs = types.MethodType(export_decoder_dummy_inputs, decoder_model)
>     decoder_model.export_input_names = types.MethodType(export_decoder_input_names, decoder_model)
>     decoder_model.export_output_names = types.MethodType(export_decoder_output_names, decoder_model)
>     decoder_model.export_dynamic_axes = types.MethodType(export_decoder_dynamic_axes, decoder_model)
>     decoder_model.export_name = types.MethodType(export_decoder_name, decoder_model)
>
>     encoder_model.export_name = 'model'
>     decoder_model.export_name = 'decoder'
> 
>     return encoder_model, decoder_model
> 
>

**Comment by LauraGPT** [comment]
Thanks a lot, we have fixed the bug: https://github.com/modelscope/FunASR/commit/e42f539eb8acd106463a5bc466a39497691fb4ca#diff-62a87ac22bc840829b47e69896d68b822d201b011ebc15042d2864077dacd59d
