### ISSUE TITLE
paraformer在CUDA 12.1/cuDNN 8.9.2推理时出现“段错误 (核心已转储)”报错

### ISSUE THREAD

**Issue by charliezcr** [modelscope/FunASR#1906]
paraformer在CUDA 12.1/cuDNN 8.9.2推理时出现“段错误 (核心已转储)”报错。之前在CUDA 11.7/cuDNN 8.5.0推理时就不会报错。确认CUDA 12.1/cuDNN 8.9.2与驱动匹配，并且在该环境下跑vllm大模型没问题，但用funasr和modelscope跑paraformer就会报错。

 - OS: Ubuntu 18.04
 - FunASR Version: 1.1.0
 - ModelScope Version: 1.16.0
 - PyTorch Version: 2.3.0+cu121
 - How you installed funasr: pip
 - Python version: 3.8
 - GPU RTX A2000 12GB
 - CUDA 12.1/cuDNN 8.9.2

**Comment by linzetian524** [comment]
我也遇到过，兄弟你解决了吗？
