### ISSUE TITLE
FunASR 离线 GPU版本 使用FunASR/runtime/run_server.sh 启动后，语音能成功解析，但是nvidia-smi看不到对应进程，怎么确定是真实使用gpu??

### ISSUE THREAD

**Issue by jiangxia207** [modelscope/FunASR#1908]
![image](https://github.com/modelscope/FunASR/assets/2645658/aa3dfa70-e1a4-40d3-9dba-4aa3c3d4f539)

docker里面启动run_server 或者 直接启动， nvidia-smi都看不到对应进程

**Comment by jiangxia207** [comment]
还是说 一定要用python 启动才行

**Comment by jiangxia207** [comment]
已解决

**Comment by lanyuer** [comment]
怎么解决的啊
