### ISSUE TITLE
多线程去做实时语音识别操作报错问题求助

### ISSUE THREAD

**Issue by PeaceAndJoyAaron** [modelscope/FunASR#1915]
#### What is your question?
我想对模型进行一个简单的压测，在做多线程调用的时候，报错：
![image](https://github.com/user-attachments/assets/11bd9df5-e3da-4092-87de-29080c51572e)
以及
![image](https://github.com/user-attachments/assets/0e0d27fc-a890-461d-8dda-516a30daa7ec)
但是报错并不是一定出现的

#### Code
`import time
import threading
from funasr import AutoModel  # 请确认funasr库和AutoModel导入正确
import soundfile
import os
import numpy as np
import shutil
import uuid

model = AutoModel(model="speech_paraformer_asr_nat-zh-cn-16k-common-vocab8404-online", model_revision="v2.0.4")

chunk_size = [0, 10, 5]  # [0, 10, 5] 600ms, [0, 8, 4] 480ms
encoder_chunk_look_back = 4  # encoder自注意力机制的回溯块数
decoder_chunk_look_back = 1  # decoder交叉注意力机制的回溯块数

original_wav_file = os.path.join(model.model_path, "example/output.wav")

lock = threading.Lock()
model_lock = threading.Lock()  # 用于模型调用的锁
total_text_length = 0
total_time_difference = 0
total_processing_time = 0
total_file_reading_time = 0
num_threads = 2  # 可以根据需要调整线程数量
results = []  # 存储每个线程的识别结果

def process_audio():
    global total_text_length, total_time_difference, total_processing_time, total_file_reading_time

    random_str = str(uuid.uuid4())[:8]  # 取前8位作为文件名
    copy_wav_file = f"output_{random_str}.wav"

    try:
        # 复制示例音频文件作为副本
        shutil.copyfile(original_wav_file, copy_wav_file)

        # 文件读取开始时间
        file_read_start_time = time.time()

        # 每个线程使用独立的音频文件副本
        speech, sample_rate = soundfile.read(copy_wav_file)

        # 如果音频是双声道，将其转换为单声道
        if speech.ndim > 1:
            speech = np.mean(speech, axis=1)

        chunk_stride = chunk_size[1] * int(sample_rate * 0.6)  # 600ms
        total_chunk_num = int((len(speech) - 1) / chunk_stride + 1)
        thread_result = []  # 存储当前线程的识别结果

        # 文件处理开始时间
        file_start_time = time.time()
        for i in range(total_chunk_num):
            speech_chunk = speech[i * chunk_stride:(i + 1) * chunk_stride]

            # 确保speech_chunk的大小一致
            if len(speech_chunk) < chunk_stride:
                padding = np.zeros(chunk_stride - len(speech_chunk))
                speech_chunk = np.concatenate((speech_chunk, padding))

            is_final = i == total_chunk_num - 1
            if is_final:
                file_read_end_time = time.time()
                file_reading_time = file_read_end_time - file_read_start_time
                # 更新文件读取时间
                with lock:
                    total_file_reading_time += file_reading_time
            # with model_lock:  # 在调用模型时加锁
            res = model.generate(input=speech_chunk, cache={}, is_final=is_final,
                                 chunk_size=chunk_size, encoder_chunk_look_back=encoder_chunk_look_back,
                                 decoder_chunk_look_back=decoder_chunk_look_back)

            # 添加识别结果到当前线程的结果列表
            thread_result.extend(res)

            # 统计text中字符数量
            text_length = sum(len(item['text']) for item in res)

            # 加锁更新全局计数
            with lock:
                total_text_length += text_length

        # 最后一块处理结束时间
        final_chunk_time = time.time()
        time_difference = final_chunk_time - file_read_end_time
        processing_time = final_chunk_time - file_read_start_time

        # 加锁更新全局时间
        with lock:
            total_time_difference += time_difference
            total_processing_time += processing_time

        # 将当前线程的识别结果添加到全局结果列表
        with lock:
            results.append(thread_result)

    except Exception as e:
        print(f"Error in thread: {str(e)}")

    finally:
        # 删除线程使用的音频文件副本，释放资源
        if os.path.exists(copy_wav_file):
            os.remove(copy_wav_file)

threads = []
for _ in range(num_threads):
    thread = threading.Thread(target=process_audio)
    threads.append(thread)
    thread.start()

for thread in threads:
    thread.join()

for idx, result in enumerate(results):
    print(f"Thread {idx + 1} result:")
    for item in result:
        print(f"  {item['text']}", end="")

average_file_reading_time = total_file_reading_time / num_threads
average_time_difference = total_time_difference / num_threads
average_processing_time = total_processing_time / num_threads
average_time_per_char = total_processing_time / total_text_length if total_text_length > 0 else 0

print(f"\nAverage file reading time per thread: {average_file_reading_time:.2f} seconds")
print(f"Average time difference per thread: {average_time_difference:.2f} seconds")
print(f"Average processing time per thread: {average_processing_time:.2f} seconds")
print(f"Average time per character: {average_time_per_char:.4f} seconds")
`
#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.27):
 - ModelScope Version (e.g., 1.14.0):
 - PyTorch Version (e.g., 2.3.0):

**Comment by PeaceAndJoyAaron** [comment]
如果在调用模型的时候加锁的话，就不会有这个问题，但是感觉这样就失去了多线程的意义了，请问这是我的代码的问题，还是模型本身的问题，期望回复

**Comment by LauraGPT** [comment]
1、theading is useless for python in calculate task.

2、For the error, we had fixed the bug:
https://github.com/modelscope/FunASR/blob/main/funasr/auto/auto_model.py#L267

You could update funasr-1.1.4
