### ISSUE TITLE
实时语音识别结合标点检测效果不好,是正常的吗

### ISSUE THREAD

**Issue by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [modelscope/FunASR#1918]

**Comment by linmingren** [comment]
实时语音识别的效果连300块钱的电话手表的识别效果都远远比不上，这种功能就不应该加在文档里让大家浪费时间。

**Comment by LauraGPT** [comment]
> _No description provided._

Show the case.

**Comment by linmingren** [comment]
> > _No description provided._
> 
> Show the case.

对不起！调整了参数，现在本地从麦克风实时识别诗词，挺准确。

**Comment by LauraGPT** [comment]
> > > _No description provided._
> > 
> > 
> > Show the case.
> 
> 对不起！调整了参数，现在本地从麦克风实时识别诗词，挺准确。

You could test it on www.funasr.com

**Comment by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [comment]
用的哪个标点预测模型啊

**Comment by Luckyin** [comment]
> > > _No description provided._
> > 
> > 
> > Show the case.
> 
> 对不起！调整了参数，现在本地从麦克风实时识别诗词，挺准确。

请问参数怎么调整的呀，我本地测试效果好像也不是很好，实时的识别
