### ISSUE TITLE
使用离线paraformer-large-长音频版的模型进行推理，出现Segmentation fault

### ISSUE THREAD

**Issue by lrs02** [modelscope/FunASR#1920]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
使用离线paraformer-large-长音频版的模型进行推理，出现Segmentation fault。之前进行推理时完全没有问题，对模型进行多进程推理实验时，未放在后台进行运行，服务器突然断开，导致四个进程消失，后续重新的跑的时候，每当进行多进程推理时，进程都会变成僵尸进程。为查找原因，从单进程单音频进行推理，出现Segmentation fault错误。

#### Code
def inference_streaming3(wav_file,gpu_id=None):
    # model_p: 使用模型路径
    #
    model_p = "/mnt/liruishan/.cache/modelscope/hub/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch-long/model_large_long"
    vad_model_p = "/mnt/liruishan/.cache/modelscope/hub/iic/FSMN_VAD_16"
    ## 使用vad
    model = AutoModel(model = model_p,vad_model = vad_model_p,device=f"cuda:{gpu_id}")
    # model = AutoModel(model = model_p,vad_model = vad_model_p)
    ## 不使用vad
    # model = AutoModel(model = model_p)
    res = model.generate(input=wav_file, 
            batch_size_s = 300, hotword='魔搭')
    #res = model.generate(input=wav_file)
    return res

#### What's your environment?

 - OS (e.g., Linux) :CentOS Linux release 7.8.2003 (Core)
 - FunASR Version (e.g., 1.0.0): 1.1.2
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):2.3.1
 - How you installed funasr (`pip`, source): pip
 - Python version: 3.12
 - GPU (e.g., V100M32) p100
 - CUDA/cuDNN version (e.g., cuda11.7): 12.3
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by lrs02** [comment]
经检查有内核报错。
![微信图片_20240717154230](https://github.com/user-attachments/assets/5b26ebb9-17c2-4dd4-a64c-7ebbba74a17a)

**Comment by LauraGPT** [comment]
Please check you torchaudio version

**Comment by qiufengyuyi** [comment]
> Please check you torchaudio version

i met the same problem ,you mean torchaudio must upgrade to the newest version?
