### ISSUE TITLE
model not registered

### ISSUE THREAD

**Issue by Lixi20** [modelscope/FunASR#1921]
path_asr = "iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model"
path_vad = "iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/model"
path_punc = "iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch/model"

model = AutoModel(
    model=path_asr,
    model_revision="v2.0.4",
    vad_model=path_vad,
    vad_model_revision="v2.0.4",
    punc_model=path_punc,
    punc_model_revision="v2.0.4",
)

报错：

AssertionError: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model is not registered

**Comment by FriendChi** [comment]
怎么解决的

**Comment by SimonComing** [comment]
好几个模型会报这个，有些模型不会，这是什么原因？

**Comment by Lixi20** [comment]
> 好几个模型会报这个，有些模型不会，这是什么原因？

我也不知道具体原因，我后面换了模型，代码如下：
`path_model = "/root/.cache/modelscope/hub/iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn"
path_vad = "/root/.cache/modelscope/hub/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch"
path_punc = "/root/.cache/modelscope/hub/iic/punc_ct-transformer_cn-en-common-vocab471067-large"

path_model = path_model if os.path.exists(path_model) else "iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn"
path_vad = path_vad if os.path.exists(path_vad) else "iic/speech_fsmn_vad_zh-cn-16k-common-pytorch"
path_punc = path_punc if os.path.exists(path_punc) else "iic/punc_ct-transformer_cn-en-common-vocab471067-large"
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model=path_model,
    model_revision='v2.0.4',
    vad_model=path_vad,
    vad_model_revision="v2.0.4",
    punc_model=path_punc,
    punc_model_revision="v2.0.4",
    output_dir=output_dir,
)
print(rec_result)
`
可以试试先将模型下载到本地看看

**Comment by Lixi20** [comment]
@SimonComing

**Comment by SimonComing** [comment]
> > 好几个模型会报这个，有些模型不会，这是什么原因？
> 
> 我也不知道具体原因，我后面换了模型，代码如下： `path_model = "/root/.cache/modelscope/hub/iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn" path_vad = "/root/.cache/modelscope/hub/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch" path_punc = "/root/.cache/modelscope/hub/iic/punc_ct-transformer_cn-en-common-vocab471067-large"
> 
> path_model = path_model if os.path.exists(path_model) else "iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn" path_vad = path_vad if os.path.exists(path_vad) else "iic/speech_fsmn_vad_zh-cn-16k-common-pytorch" path_punc = path_punc if os.path.exists(path_punc) else "iic/punc_ct-transformer_cn-en-common-vocab471067-large" inference_pipeline = pipeline( task=Tasks.auto_speech_recognition, model=path_model, model_revision='v2.0.4', vad_model=path_vad, vad_model_revision="v2.0.4", punc_model=path_punc, punc_model_revision="v2.0.4", output_dir=output_dir, ) print(rec_result) ` 可以试试先将模型下载到本地看看 @SimonComing @FriendChi

今天找到原因了，不能直接用模型仓库中的模型名字，要用模型ModelScope页面的地址才行。比如我之前给model变量赋值paraformer-zh-spk，这样不行要赋值为iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn，这个才行。

**Comment by BOCEAN-FENG** [comment]
您好，我按照您的方法以这个连接为例：https://www.modelscope.cn/models/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary
![捕获](https://github.com/user-attachments/assets/df73be23-ac30-40ba-8758-dab9ffbf752c)
将模型设置为iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch。代码是：


from funasr import AutoModel
# paraformer-zh is a multi-functional asr model
# use vad, punc, spk or not as you need
model = AutoModel(model="iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", model_revision="v2.0.4"
                  )
res = model.generate(input=f"D:\\000.wav",
            batch_size_s=300,
            hotword='魔搭')

print(res[0]['text'])


为什么仍然会提示AssertionError: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch is not registered？不知道是不是我的理解不对？

**Comment by FriendChi** [comment]
建议去掉iic/试试

**Comment by BOCEAN-FENG** [comment]
![捕获6666](https://github.com/user-attachments/assets/14eda760-8eda-4425-8558-92acd491f336)
感谢回答，但是仍然报错，我连个quick start都跑不出来了

**Comment by FriendChi** [comment]
别用他这个了，直接使用魔塔的管道吧

**Comment by FriendChi** [comment]
@BOCEAN-FENG 也许你应该在路径iic前面再加上/root/.cache/modelscope/hub/

**Comment by BOCEAN-FENG** [comment]
再次感谢您的回答，但是还是报错，下午用的时候，同样的代码有一段时间可以跑通，然后我记得下载了一些模型，但是实在是找不到路径了。之后我发现再跑同样的代码就一点也跑不通了。这给我搞炸了要
![666666666](https://github.com/user-attachments/assets/77920d23-40d0-4507-ab6f-1c7352c86481)

**Comment by BOCEAN-FENG** [comment]
> @BOCEAN-FENG 也许你应该在路径iic前面再加上/root/.cache/modelscope/hub/

原因是魔塔官网的证书今天过期了，需要清一下电脑的SSL,感谢您的回答

**Comment by leavegee** [comment]
把版本参数去掉

**Comment by komAAmok** [comment]
@BOCEAN-FENG 这样也行，model = AutoModel(
    model="paraformer-zh", model_revision="v2.0.5",
    vad_model="fsmn-vad", vad_model_revision="v2.0.4",
    punc_model="ct-punc-c", punc_model_revision="v2.0.4",
    spk_model="cam++", spk_model_revision="v2.0.2",
    disable_update=True,
    model_hub="ms",
    disable_pbar=True
)

**Comment by loopback00** [comment]
我是把路径删除，然后重新把路径填上就好了，搞不懂
