### ISSUE TITLE
多线程实时语音识别，结果会互相干扰 [CPU]

### ISSUE THREAD

**Issue by Helloooxs** [modelscope/FunASR#1922]
尽管在调用generate时加了锁，还是会出现A线程的结果，部分和B线程的结果混在一起，互相交叉输出
感觉原因是因为chunk_size中[back, size, ahead]，back和ahead的部分，多线程是没法处理的？有什么解决方案吗？有没有参数能解决这个事情？
我把chunk_size设成[0, n, 1]，只给60ms的ahead，错乱的情况明显就好多了，

ENCODER_CHUNK_LOOK_BACK = 4
DECODER_CHUNK_LOOK_BACK = 1
chunk_size = [0, CHUNK_SIZE, 1]

decoded_text = self.streamEngine.generate(
                    input=in_bytes,
                    cache=cache,
                    is_final=False,
                    chunk_size=chunk_size,
                    encoder_chunk_look_back=ENCODER_CHUNK_LOOK_BACK,
                    decoder_chunk_look_back=DECODER_CHUNK_LOOK_BACK,
                    # sentence_timestamp=True
                )

**Comment by Helloooxs** [comment]
尝试设成[0, n, 0]，但是结果会一直重复输出，不可用

**Comment by LauraGPT** [comment]
你需要把cache独立开，每一条线cache单独定义和调用
