### ISSUE TITLE
spk_mode设为vad_segment时推理出错

### ISSUE THREAD

**Issue by liugz18** [modelscope/FunASR#1927]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）
![bugreport1](https://github.com/user-attachments/assets/7d60fda4-ce80-44da-9d0e-f6e1a7428af5)

#### What is your question?
如图，spk_mode设为vad_segment时，inference_with_vad()的res会变成dict而不是list

#### What have you tried?
读源代码，还一无所获
#### What's your environment?

 - OS (Ubuntu):
 - FunASR Version (latest version of funasr-1.1.2):

**Comment by LauraGPT** [comment]
Thanks
