### ISSUE TITLE
初始化就需要40秒左右算正常吗

### ISSUE THREAD

**Issue by zh-nj** [modelscope/FunASR#1931]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

如题
model = AutoModel(model="/mnt/DATA/models/speech_fsmn_vad_zh-cn-16k-common-pytorch", model_revision="v2.0.4")
这个非常小的Vad，其他模型都差不多。

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
The time cost mainly exists in version check, you could del it: https://github.com/modelscope/FunASR/blob/main/funasr/auto/auto_model.py#L117

**Comment by zh-nj** [comment]
thanks a lot!
