### ISSUE TITLE
找不到文件，但文件确定是有的。

### ISSUE THREAD

**Issue by yourengod** [modelscope/FunASR#1932]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help
找不到文件。E20240719 11:35:01.428516 217784 funasr-wss-server-2pass.cpp:247] ~/workspace/myfunasr/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/model_quant.onnx do not exists.

运行“ bash run_server_2pass.sh ”时报的错。但是文件确定是有的。

**Comment by littlestone0806** [comment]
我也遇到了这个问题，请问当时是如何解决的？
