### ISSUE TITLE
可以支持实时语音识别翻译为中文吗

### ISSUE THREAD

**Issue by mushan0x0** [modelscope/FunASR#1936]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

#### What is your question?

现在只有 Whisper 的模型支持翻译，但只能中译英，请问是否有英译中的

而且 Whisper 的翻译只能输出翻译后的内容，并没有原始内容😢

**Comment by mushan0x0** [comment]
[逆文本正则化](https://github.com/modelscope/FunASR/blob/85c1675e7cf4ee036a1fdeded4da8426f1775d8a/model_zoo/modelscope_models_zh.md#%E9%80%86%E6%96%87%E6%9C%AC%E6%AD%A3%E5%88%99%E5%8C%96) 是不是少了中文的

**Comment by LauraGPT** [comment]
No support now.
