### ISSUE TITLE
FunASR实时语音转写是否有C++版本的实现源代码？

### ISSUE THREAD

**Issue by lqzzy** [modelscope/FunASR#1944]
## ❓ Questions and Help
我找到了windows上和linux上服务端的部署文档，比如 https://www.modelscope.cn/damo/funasr-runtime-win-cpu-x64.git 中，他中间有windows上的部署方法，但是其中只包含了.exe文件，我希望能够看到C/C++文件和CMakeList，以及如何从C++源码开始部署实时语音转写服务，因为我有一些个性化的需求需要修改实时语音服务的代码。

### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
我希望能够找到FunASR软件编译之前的C++源代码和CMakeList，以及编译的环境和运行的方法，帮助我从源码安装FunASR。

**Comment by LauraGPT** [comment]
www.funasr.com
