### ISSUE TITLE
标点符号问题

### ISSUE THREAD

**Issue by yourengod** [modelscope/FunASR#1945]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help
你好，你是谁。这是识别结果，这个最后不应该是问号吗？怎么是句号啊？如下图所示：
![Screenshot_2024 07 23_10 29 50 078](https://github.com/user-attachments/assets/18419f1d-d57a-462f-b1ee-e8a0591489e8)

**Comment by yourengod** [comment]
> You could test it on https://www.modelscope.cn/studios/iic/SenseVoice
> 
> ![image](https://private-user-images.githubusercontent.com/18321252/351207732-4ed9a6fc-59eb-4084-8743-1975fce2e786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTU5NjEsIm5iZiI6MTcyMTcxNTY2MSwicGF0aCI6Ii8xODMyMTI1Mi8zNTEyMDc3MzItNGVkOWE2ZmMtNTllYi00MDg0LTg3NDMtMTk3NWZjZTJlNzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA2MjEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZThiNTEyMGUzNTM2ZWVmODkwMzFjZTZmY2Q2OTQ3OTY0OTNjNjJlYjMxNzFhNTM3NmJkOGVkN2Q5N2M5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kTbhVO3LKyPdsdHPKBKf6XjR8QvEcQawZGRFqSjKdyk)

您好，这个是sensevoice的吧？我请教的是funasr的。而且sensevoice没有生产环境下的语言吧，比如c++版本的。

**Comment by csukuangfj** [comment]
> 而且sensevoice没有生产环境下的语言吧，比如c++版本的

你可以看下 [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)， 支持 sensevoice, 支持c/c++等10种语言中使用 sense voice.
