### ISSUE TITLE
funasr in /usr/local/lib/python3.10/dist-packages (1.1.3)  模型训练与测试时报错  ModuleNotFoundError: No module named 'funasr.download.download_from_hub'

### ISSUE THREAD

**Issue by taiyuanbj** [modelscope/FunASR#1951]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### To Reproduce

funasr in /usr/local/lib/python3.10/dist-packages (1.1.3)

run:
Python 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from funasr.download.download_from_hub import download_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'funasr.download.download_from_hub'
>>> 

=====================================
W0723 23:37:18.815000 127105130606592 torch/distributed/run.py:757] 
W0723 23:37:18.815000 127105130606592 torch/distributed/run.py:757] *****************************************
W0723 23:37:18.815000 127105130606592 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0723 23:37:18.815000 127105130606592 torch/distributed/run.py:757] *****************************************
Traceback (most recent call last):
  File "/home/zhou/funasr/FunASR/examples/industrial_data_pretraining/paraformer/../../../funasr/bin/train_ds.py", line 30, in <module>
    from funasr.download.download_from_hub import download_model
ModuleNotFoundError: No module named 'funasr.download.download_from_hub'
Traceback (most recent call last):
  File "/home/zhou/funasr/FunASR/examples/industrial_data_pretraining/paraformer/../../../funasr/bin/train_ds.py", line 30, in <module>
    from funasr.download.download_from_hub import download_model
ModuleNotFoundError: No module named 'funasr.download.download_from_hub'
E0723 23:37:23.822000 127105130606592 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 230500) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../../../funasr/bin/train_ds.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-23_23:37:23
  host      : zhou
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 230501)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-23_23:37:23
  host      : zhou
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 230500)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):pip3
 - Python version:3.10.12
 - GPU (e.g., 4090)
 - Any other relevant information:

**Comment by wuhongsheng** [comment]
> Notice: In order to resolve issues more efficiently, please raise issue following the template. （注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）
> 
> ## 🐛 Bug
> ### To Reproduce
> funasr in /usr/local/lib/python3.10/dist-packages (1.1.3)
> 
> run: Python 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from funasr.download.download_from_hub import download_model
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > ModuleNotFoundError: No module named 'funasr.download.download_from_hub'
> 
> # =====================================
> W0723 23:37:18.815000 127105130606592 torch/distributed/run.py:757]
> W0723 23:37:18.815000 127105130606592 torch/distributed/run.py:757] *****************************************
> W0723 23:37:18.815000 127105130606592 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> W0723 23:37:18.815000 127105130606592 torch/distributed/run.py:757] *****************************************
> Traceback (most recent call last):
> File "/home/zhou/funasr/FunASR/examples/industrial_data_pretraining/paraformer/../../../funasr/bin/train_ds.py", line 30, in
> from funasr.download.download_from_hub import download_model
> ModuleNotFoundError: No module named 'funasr.download.download_from_hub'
> Traceback (most recent call last):
> File "/home/zhou/funasr/FunASR/examples/industrial_data_pretraining/paraformer/../../../funasr/bin/train_ds.py", line 30, in
> from funasr.download.download_from_hub import download_model
> ModuleNotFoundError: No module named 'funasr.download.download_from_hub'
> E0723 23:37:23.822000 127105130606592 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 230500) of binary: /usr/bin/python3
> Traceback (most recent call last):
> File "/usr/local/bin/torchrun", line 8, in
> sys.exit(main())
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 347, in wrapper
> return f(*args, **kwargs)
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 879, in main
> run(args)
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 870, in run
> elastic_launch(
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in **call**
> return launch_agent(self._config, self._entrypoint, list(args))
> File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
> raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ## ../../../funasr/bin/train_ds.py FAILED
> ## Failures:
> [1]:
> time : 2024-07-23_23:37:23
> host : zhou
> rank : 1 (local_rank: 1)
> exitcode : 1 (pid: 230501)
> error_file: <N/A>
> traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> # Root Cause (first observed failure):
> [0]:
> time : 2024-07-23_23:37:23
> host : zhou
> rank : 0 (local_rank: 0)
> exitcode : 1 (pid: 230500)
> error_file: <N/A>
> traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ### Expected behavior
> ### Environment
> * OS (e.g., Linux):
> * FunASR Version (e.g., 1.0.0):
> * ModelScope Version (e.g., 1.11.0):
> * PyTorch Version (e.g., 2.0.0):
> * How you installed funasr (`pip`, source):pip3
> * Python version:3.10.12
> * GPU (e.g., 4090)
> * Any other relevant information:
> 
> ### Additional context

你好，我遇到同样的问题，怎么解决的

**Comment by benzhangdragonplus** [comment]
Modify the import to：**download_model_from_hub**

**from funasr.download.download_model_from_hub import download_model**

https://github.com/modelscope/FunASR/blob/main/funasr/download/download_model_from_hub.py
