### ISSUE TITLE
    public static final String CHUNK_SIZE = "5, 10, 5"这几个5,10表示什么意思？

### ISSUE THREAD

**Issue by yourengod** [modelscope/FunASR#1952]
## ❓ Questions and Help
"5, 10, 5"，表示往前看5*60，取当前长度10*60，向后看5*60，单位毫秒。请问：这几个5，10怎么来的啊？表示什么，10和短时稳定有关吗？跟帧移有关吗？

**Comment by LauraGPT** [comment]
1 frame=60ms

**Comment by sanwei111** [comment]
> 1 frame=60ms

会看+又看等于总长？
