### ISSUE TITLE
进入容器运行后，退出容器，容器立刻关闭

### ISSUE THREAD

**Issue by leavegee** [modelscope/FunASR#1976]
# 启动docker
sudo docker run -p 10095:10095 -it --privileged=true \
  -v $PWD/funasr-runtime-resources/models:/workspace/models \
  funasr:funasr-runtime-sdk-cpu-0.4.5
  
# 进入容器启动服务  
cd FunASR/runtime
nohup bash run_server.sh \
  --download-model-dir /workspace/models \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --model-dir damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
  --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
  --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
  --itn-dir thuduj12/fst_itn_zh \
  --hotword /workspace/models/hotwords.txt > log.txt 2>&1 &

这是我的运行脚本。  一直保持在容器里面是可以运行的。 但是 一旦退出容器或者关闭终端， 容器立刻就关闭了。

**Comment by LauraGPT** [comment]
You could learn the usage of docker by google.
