### ISSUE TITLE
Whisper is translating my non-English audio into English

### ISSUE THREAD

**Issue by Bien9x** [modelscope/FunASR#1977]
How can I adjust the output transcription to match the input audio? It always returns English text, even though I've specified the target language parameter as shown in this [example](https://github.com/modelscope/FunASR/blob/main/examples/industrial_data_pretraining/whisper/demo.py). Could this be a bug?

#### Code
from funasr import AutoModel

model = AutoModel(
    model="Whisper-large-v3",
    vad_model="speech_fsmn_vad_zh-cn-16k-common-pytorch",
    vad_kwargs={"max_single_segment_time": 30000},
)

DecodingOptions = {
    "task": "transcribe",
    "language": "vi",
    "beam_size": None,
    "fp16": True,
    "without_timestamps": False,
    "prompt": None,
}
res = model.generate(
    DecodingOptions=DecodingOptions,
    batch_size_s=0,
    "aud.wav",
)

print(res)

 - OS: Linux
 - FunASR Version: 1.1.4
 - ModelScope Version: 1.16.1
 - PyTorch Version : 2.3.1
 - How you installed funasr: pip
 - Python version: 3.10.12
 - GPU: T4
 - CUDA/cuDNN version: 12.2
 - Env: Colab

**Comment by LauraGPT** [comment]
Sorry, we would fix it soon.

**Comment by LauraGPT** [comment]
Bugfix: https://github.com/modelscope/FunASR/commit/7f6099140a781bd18115bd82a5dd0525d43af290
