### ISSUE TITLE
按照首页教程执行后报错:AssertionError: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch is not registered

### ISSUE THREAD

**Issue by BOCEAN-FENG** [modelscope/FunASR#1981]
环境如下：
python==3.11
torch==2.1.0
torchaudio==2.1.0

代码如下：
from funasr import AutoModel
# paraformer-zh is a multi-functional asr model
# use vad, punc, spk or not as you need

model = AutoModel(model="iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", model_revision="v2.0.4"
                  )
res = model.generate(input=f"D:\\001.wav",
            batch_size_s=300,
            hotword='魔搭')

print(res[0]['text'])

报错如下：
You are using the latest version of funasr-1.1.4
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=2, read=2, redirect=None, status=None)) after connection broken by 'SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)')': /api/v1/models/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=2, read=2, redirect=None, status=None)) after connection broken by 'SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)')': /api/v1/models/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions
Download: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch failed!: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)')))
Traceback (most recent call last):
  File "D:\T\TEST.py", line 7, in <module>
    model = AutoModel(model="iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", model_revision="v2.0.4"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\T\.venv\Lib\site-packages\funasr\auto\auto_model.py", line 124, in __init__
    model, kwargs = self.build_model(**kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\T\.venv\Lib\site-packages\funasr\auto\auto_model.py", line 218, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch is not registered

Process finished with exit code 1

本来以为是加速器问题，但是不管开关都报错。之前同样的代码执行没有问题，隔一段时间就开始报not registered的错误，但是模型明明已经下载到本地,为什么还是提示：Download: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch failed!

**Comment by BOCEAN-FENG** [comment]
原因是魔塔官网的证书今天过期了，需要清一下电脑的SSL

**Comment by SixGoodX** [comment]
> 原因是魔塔官网的证书今天过期了，需要清一下电脑的SSL

有用吗？具体为什么会出现这种情况啊？怎么清理电脑的SSL呢
