### ISSUE TITLE
使用speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch模型进行微调，导入模型失败。

### ISSUE THREAD

**Issue by xipingL** [modelscope/FunASR#1990]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
使用finetune微调模型生成的output文件中有对应的model.pt和configuration.json,看文档https://github.com/modelscope/FunASR/blob/main/docs/tutorial/README_zh.md，只需要AutoModel(model="./output")应该就可以了，但是报错
Traceback (most recent call last):
  File "C:\Users\root\Desktop\workspace\funasr\FunASR-main\examples\industrial_data_pretraining\paraformer\tt.py", line 3, in <module>
    model = AutoModel(model= "./output")
  File "c:\users\root\desktop\workspace\funasr\funasr-main\funasr\auto\auto_model.py", line 127, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "c:\users\root\desktop\workspace\funasr\funasr-main\funasr\auto\auto_model.py", line 222, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
AssertionError: ./output is not registered

#### Code
from funasr import AutoModel

model = AutoModel(model= "./output")

res = model.generate(input="https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav")
print(res)

感谢
#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by YMMF007** [comment]
您好，我也遇到了这个问题，请问您是怎么解决的呀

**Comment by kill2013110** [comment]
> 您好，我也遇到了这个问题，请问您是怎么解决的呀

同一个问题，怎么解决的啊
