### ISSUE TITLE
关于funasr 4.5 的docker包的问题改进

### ISSUE THREAD

**Issue by dfengpo** [modelscope/FunASR#2002]
希望能解决以下问题，针对funasr 4.5-cpu 的docker包
1，支持不了并发，只要服务中有未完成任务，这个时候再发送数据，后台服务就直接死掉了重启了
2，当发送文件无效，服务处理出错时，也应该给客户端返回处理错误信息，便于客户端判断处理

**Comment by LauraGPT** [comment]
Maybe you could test it on: www.funasr.com
