### ISSUE TITLE
用funasr加载SenseVoiceSmall模型提示 not registered

### ISSUE THREAD

**Issue by dsyrock** [modelscope/FunASR#2003]
#### Code
```
from funasr import AutoModel
model = AutoModel(model=p.model)
```

p.model是我传入的参数，是我已经下载好的SenseVoiceSmall模型的路径

然后提示我：AssertionError: C: \REAPER\UserPlugins\funasr \SenseVoiceSmall is not registered 

 - OS: Win10
 - FunASR Version: 1.1.4

**Comment by LauraGPT** [comment]
Please check your `p.model`.

**Comment by dsyrock** [comment]
> Please check your `p.model`.

ok谢了，原来是我文件夹里的文件没放全
