### ISSUE TITLE
runtime/csharp/ws-client/FunASRWSClient_Offline 项目不支持并发

### ISSUE THREAD

**Issue by dfengpo** [modelscope/FunASR#2013]
我通过以下项目
https://github.com/modelscope/FunASR/tree/main/runtime/csharp/ws-client/FunASRWSClient_Offline
启动docker完全是按照以下文档
https://github.com/modelscope/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md
在本地给远程云服务器部署的docker cpu 4.5版本发送文件，当服务已经有文件在处理中的时候，我再发一条录音数据过去，
服务就直接死掉重启了

只要一开并发，识别服务器就直接启动了

要支持并发是需要单独配置以下参数吗
--decoder-thread-num  服务端线程池个数(支持的最大并发路数)，
                      脚本会根据服务器线程数自动配置decoder-thread-num、io-thread-num
--io-thread-num  服务端启动的IO线程数
--model-thread-num  每路识别的内部线程数(控制ONNX模型的并行)，默认为 1，

**Comment by lyblsgo** [comment]
这是社区用户开发的客户端，建议使用使用官方维护的c++或者python客户端
