### ISSUE TITLE
docker部署funasr，镜像是funasr-runtime-sdk-cpu-0.4.5，如何识别不同人说话

### ISSUE THREAD

**Issue by jaychuo** [modelscope/FunASR#2033]
## ❓ Questions and Help
用docker部署funasr，镜像是funasr-runtime-sdk-cpu-0.4.5，如何实现服务端返回报文包含spk字段，识别说话人？谢谢！

**Comment by lyblsgo** [comment]
目前暂不支持，支持后会钉钉群发布通知
