### ISSUE TITLE
当我通过run_server.sh使用SenseVoiceSmall模型时出现错误:models/iic/SenseVoiceSmall/model_quant.onnx do not exists.

### ISSUE THREAD

**Issue by firekirin67** [modelscope/FunASR#2035]
## ❓ Questions and Help
当我通过run_server.sh使用SenseVoiceSmall模型时出现错误

提示错误信息:models/iic/SenseVoiceSmall/model_quant.onnx do not exists.

#### Code
通过在run_server.sh文件修改脚本代码如下:
#model_dir="damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx"
model_dir="iic/SenseVoiceSmall"
#vad_dir="damo/speech_fsmn_vad_zh-cn-16k-common-onnx"
vad_dir=""
#punc_dir="damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx"
punv_dir=""
#itn_dir="thuduj12/fst_itn_zh"
itn_dir=""
#lm_dir="damo/speech_ngram_lm_zh-cn-ai-wesp-fst"

#### What's your environment?

 - OS (e.g., Linux): Linux
 - FunASR Version (e.g., 1.1.6):1.1.6
 - ModelScope Version (e.g., 1.11.0):1.11.0
 - PyTorch Version (e.g., 2.0.0):8.32
 - How you installed funasr (`pip`, source): source
 - Python version:3.1.16

**Comment by lyblsgo** [comment]
已支持SensevoiceSmall，部署参考https://github.com/modelscope/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md

**Comment by LinFei83** [comment]
> > 已支持SensevoiceSmall，部署参考https://github.com/modelscope/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md
> 
> 使用docker部署也有这个问题, 并不是"iic/SenseVoiceSmall-onnx"呀 配置如下: `docker-compose.yml`
> 
> ```
> version: "3.8"
> 
> services:
>   funasr:
>     image: registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.13
>     container_name: funasr_runtime012
>     privileged: true
>     ports:
>       - "10096:10095"
>     volumes:
>       - ./funasr-runtime-resources/models:/workspace/models
>       - ./run_server_2pass.sh:/workspace/FunASR/runtime/run_server_2pass.sh
>     working_dir: /workspace/FunASR/runtime
>     command: >
>       bash -c "
>       nohup bash run_server_2pass.sh\
>         --hotword /workspace/models/hotwords.txt > log.txt 2>&1 &
>       tail -f log.txt
>       "
> ```
> 
> `run_server_2pass.sh`
> 
> ```
> download_model_dir="/workspace/models"
> model_dir="iic/SenseVoiceSmall"
> online_model_dir="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx"
> vad_dir="damo/speech_fsmn_vad_zh-cn-16k-common-onnx"
> punc_dir="damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx"
> itn_dir="thuduj12/fst_itn_zh"
> lm_dir="damo/speech_ngram_lm_zh-cn-ai-wesp-fst"
> port=10095
> certfile="$(pwd)/ssl_key/server.crt"
> keyfile="$(pwd)/ssl_key/server.key"
> hotword="$(pwd)/websocket/hotwords.txt"
> # set decoder_thread_num
> decoder_thread_num=$(cat /proc/cpuinfo | grep "processor"|wc -l) || { echo "Get cpuinfo failed. Set decoder_thread_num = 32"; decoder_thread_num=32; }
> multiple_io=16
> io_thread_num=$(( (decoder_thread_num + multiple_io - 1) / multiple_io ))
> model_thread_num=1
> cmd_path=/workspace/FunASR/runtime/websocket/build/bin
> cmd=funasr-wss-server-2pass
> 
> . ./tools/utils/parse_options.sh || exit 1;
> 
> if [ -z "$certfile" ] || [ "$certfile" = "0" ]; then
>   certfile=""
>   keyfile=""
> fi
> 
> cd $cmd_path
> $cmd_path/${cmd}  \
>   --download-model-dir "${download_model_dir}" \
>   --model-dir "${model_dir}" \
>   --online-model-dir "${online_model_dir}" \
>   --vad-dir "${vad_dir}" \
>   --punc-dir "${punc_dir}" \
>   --itn-dir "${itn_dir}" \
>   --lm-dir "${lm_dir}" \
>   --decoder-thread-num ${decoder_thread_num} \
>   --model-thread-num ${model_thread_num} \
>   --io-thread-num  ${io_thread_num} \
>   --port ${port} \
>   --certfile  "${certfile}" \
>   --keyfile "${keyfile}" \
>   --hotword "${hotword}" &
> ```
> 
> 报错如下
> 
> ```
> (hugging_face) lf@framework:~/docker/FunASR/funasr-runtime-resources/models/iic/SenseVoiceSmall$ sudo docker compose up
> WARN[0000] /home/lf/docker/FunASR/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
> Attaching to funasr_runtime012
> funasr_runtime012  | bash: line 1: --hotword: command not found
> funasr_runtime012  | I20251124 11:29:43.878338    15 funasr-wss-server-2pass.cpp:25] model-dir : iic/SenseVoiceSmall
> funasr_runtime012  | I20251124 11:29:43.878402    15 funasr-wss-server-2pass.cpp:25] online-model-dir : damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx
> funasr_runtime012  | I20251124 11:29:43.878407    15 funasr-wss-server-2pass.cpp:25] quantize : true
> funasr_runtime012  | I20251124 11:29:43.878408    15 funasr-wss-server-2pass.cpp:25] vad-dir : damo/speech_fsmn_vad_zh-cn-16k-common-onnx
> funasr_runtime012  | I20251124 11:29:43.878412    15 funasr-wss-server-2pass.cpp:25] vad-quant : true
> funasr_runtime012  | I20251124 11:29:43.878414    15 funasr-wss-server-2pass.cpp:25] punc-dir : damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx
> funasr_runtime012  | I20251124 11:29:43.878417    15 funasr-wss-server-2pass.cpp:25] punc-quant : true
> funasr_runtime012  | I20251124 11:29:43.878418    15 funasr-wss-server-2pass.cpp:25] itn-dir : thuduj12/fst_itn_zh
> funasr_runtime012  | I20251124 11:29:43.878420    15 funasr-wss-server-2pass.cpp:25] lm-dir : damo/speech_ngram_lm_zh-cn-ai-wesp-fst
> funasr_runtime012  | I20251124 11:29:43.878422    15 funasr-wss-server-2pass.cpp:25] hotword : /workspace/FunASR/runtime/websocket/hotwords.txt
> funasr_runtime012  | I20251124 11:29:43.878425    15 funasr-wss-server-2pass.cpp:25] offline-model-revision : v2.0.5
> funasr_runtime012  | I20251124 11:29:43.878427    15 funasr-wss-server-2pass.cpp:25] online-model-revision : v2.0.5
> funasr_runtime012  | I20251124 11:29:43.878430    15 funasr-wss-server-2pass.cpp:25] vad-revision : v2.0.4
> funasr_runtime012  | I20251124 11:29:43.878432    15 funasr-wss-server-2pass.cpp:25] punc-revision : v2.0.5
> funasr_runtime012  | I20251124 11:29:43.878434    15 funasr-wss-server-2pass.cpp:25] itn-revision : v1.0.1
> funasr_runtime012  | I20251124 11:29:43.878436    15 funasr-wss-server-2pass.cpp:25] lm-revision : v1.0.2
> funasr_runtime012  | I20251124 11:29:43.878443    15 funasr-wss-server-2pass.cpp:225] Download model: damo/speech_fsmn_vad_zh-cn-16k-common-onnx from modelscope: 
> funasr_runtime012  | /usr/local/lib/python3.8/runpy.py:127: RuntimeWarning: 'funasr.download.runtime_sdk_download_tool' found in sys.modules after import of package 'funasr.download', but prior to execution of 'funasr.download.runtime_sdk_download_tool'; this may result in unpredictable behaviour
> funasr_runtime012  |   warn(RuntimeWarning(msg))
> funasr_runtime012  | 2025-11-24 11:29:45,882 - modelscope - INFO - Use user-specified model revision: v2.0.4
> funasr_runtime012  | Notice: ffmpeg is not installed. torchaudio is used to load audio
> funasr_runtime012  | If you want to use ffmpeg backend to load audio, please install it by:
> funasr_runtime012  |    sudo apt install ffmpeg # ubuntu
> funasr_runtime012  |    # brew install ffmpeg # mac
> funasr_runtime012  | I20251124 11:29:46.416755    15 funasr-wss-server-2pass.cpp:251] Set vad-dir : /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx
> funasr_runtime012  | I20251124 11:29:46.416816    15 funasr-wss-server-2pass.cpp:295] Download model: iic/SenseVoiceSmall from modelscope : 
> funasr_runtime012  | /usr/local/lib/python3.8/runpy.py:127: RuntimeWarning: 'funasr.download.runtime_sdk_download_tool' found in sys.modules after import of package 'funasr.download', but prior to execution of 'funasr.download.runtime_sdk_download_tool'; this may result in unpredictable behaviour
> funasr_runtime012  |   warn(RuntimeWarning(msg))
> funasr_runtime012  | Traceback (most recent call last):
> funasr_runtime012  |   File "/workspace/FunASR/funasr/download/runtime_sdk_download_tool.py", line 28, in main
> funasr_runtime012  |     model_dir = snapshot_download(
> funasr_runtime012  |   File "/usr/local/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py", line 84, in snapshot_download
> funasr_runtime012  |     return _snapshot_download(
> funasr_runtime012  |   File "/usr/local/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py", line 221, in _snapshot_download
> funasr_runtime012  |     revision_detail = _api.get_valid_revision_detail(
> funasr_runtime012  |   File "/usr/local/lib/python3.8/site-packages/modelscope/hub/api.py", line 530, in get_valid_revision_detail
> funasr_runtime012  |     raise NotExistError('The model: %s has no revision: %s !' % (model_id, revision))
> funasr_runtime012  | modelscope.hub.errors.NotExistError: The model: iic/SenseVoiceSmall has no revision: v2.0.5 !
> funasr_runtime012  | 
> funasr_runtime012  | During handling of the above exception, another exception occurred:
> funasr_runtime012  | 
> funasr_runtime012  | Traceback (most recent call last):
> funasr_runtime012  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> funasr_runtime012  |     return _run_code(code, main_globals, None,
> funasr_runtime012  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
> funasr_runtime012  |     exec(code, run_globals)
> funasr_runtime012  |   File "/workspace/FunASR/funasr/download/runtime_sdk_download_tool.py", line 58, in <module>
> funasr_runtime012  |     main()
> funasr_runtime012  |   File "/workspace/FunASR/funasr/download/runtime_sdk_download_tool.py", line 33, in main
> funasr_runtime012  |     raise "model_dir must be model_name in modelscope or local path downloaded from modelscope, but is {}".format(
> funasr_runtime012  | TypeError: exceptions must derive from BaseException
> funasr_runtime012  | Notice: ffmpeg is not installed. torchaudio is used to load audio
> funasr_runtime012  | If you want to use ffmpeg backend to load audio, please install it by:
> funasr_runtime012  |    sudo apt install ffmpeg # ubuntu
> funasr_runtime012  |    # brew install ffmpeg # mac
> funasr_runtime012  | I20251124 11:29:48.842501    15 funasr-wss-server-2pass.cpp:307] Failed to download model from modelscope. If you set local asr model path, you can ignore the errors.
> funasr_runtime012  | E20251124 11:29:48.842602    15 funasr-wss-server-2pass.cpp:316] /workspace/models/iic/SenseVoiceSmall/model_quant.onnx do not exists.
> ```

我手动下载`iic/SenseVoiceSmall`到本地目录也不太行

**Comment by LinFei83** [comment]
原因是模型库中并不存在 v2.0.5 版本，仅存在 master 分支，导致自动下载失败，进而未能触发后续的自动导出与量化流程，无法生成 model.pt 模型文件。在手动下载对应模型并指定本地路径后才可以。


`run_server_2pass.sh`
```
download_model_dir="/workspace/models"
# model_dir="iic/SenseVoiceSmall"
model_dir="/workspace/models/iic/SenseVoiceSmall"
online_model_dir="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx"
vad_dir="damo/speech_fsmn_vad_zh-cn-16k-common-onnx"
punc_dir="damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx"
itn_dir="thuduj12/fst_itn_zh"
lm_dir="damo/speech_ngram_lm_zh-cn-ai-wesp-fst"
port=10095
certfile="$(pwd)/ssl_key/server.crt"
keyfile="$(pwd)/ssl_key/server.key"
hotword="$(pwd)/websocket/hotwords.txt"
# set decoder_thread_num
decoder_thread_num=$(cat /proc/cpuinfo | grep "processor"|wc -l) || { echo "Get cpuinfo failed. Set decoder_thread_num = 32"; decoder_thread_num=32; }
multiple_io=16
io_thread_num=$(( (decoder_thread_num + multiple_io - 1) / multiple_io ))
model_thread_num=1
cmd_path=/workspace/FunASR/runtime/websocket/build/bin
cmd=funasr-wss-server-2pass

. ./tools/utils/parse_options.sh || exit 1;

if [ -z "$certfile" ] || [ "$certfile" = "0" ]; then
  certfile=""
  keyfile=""
fi

cd $cmd_path
$cmd_path/${cmd}  \
  --download-model-dir "${download_model_dir}" \
  --model-dir "${model_dir}" \
  --online-model-dir "${online_model_dir}" \
  --vad-dir "${vad_dir}" \
  --punc-dir "${punc_dir}" \
  --itn-dir "${itn_dir}" \
  --lm-dir "${lm_dir}" \
  --decoder-thread-num ${decoder_thread_num} \
  --model-thread-num ${model_thread_num} \
  --io-thread-num  ${io_thread_num} \
  --port ${port} \
  --certfile  "${certfile}" \
  --keyfile "${keyfile}" \
  --hotword "${hotword}" &
```
