### ISSUE TITLE
多段语音并行识别失败问题

### ISSUE THREAD

**Issue by MENGHAH** [modelscope/FunASR#2051]
全局asr_model初始化完成后，基于多线程进行多个音频文件的并行转写出现错误。
代码如下：
`all_dic = asr_model.generate(input=audio, batchsize=300)[0]`
error日志如下：
`    cur_decibel = cache["stats"].decibel[t]
                  ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

**Comment by LauraGPT** [comment]
不支持多线程。可以用多进程或者docker服务

**Comment by bebilli** [comment]
@LauraGPT  如果是多进程，每个进程都要重复加载模型？
