### ISSUE TITLE
speech_ngram_lm_zh-cn-ai-wesp-fst 这个模型怎么做增量训练

### ISSUE THREAD

**Issue by liuwenchang** [modelscope/FunASR#2052]
根据runtime/tools的脚本，找了一些文本语料，只能训练出一个新模型，怎么才能在默认模型上进行增量训练呢？

**Comment by lyblsgo** [comment]
看文档，定制ngram https://github.com/modelscope/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md
