### ISSUE TITLE
离线文件服务websocket解析音频后，返回的结果不对

### ISSUE THREAD

**Issue by wangguo1230** [modelscope/FunASR#2054]
## 🐛 Bug
离线文件websocket服务传入wav音频后，解析返回的结果中不包含is_final:true
镜像：registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.4.5
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

运行命令：nohup bash run_server.sh --certfile 0 --download-model-dir /workspace/models --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx --model-dir damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst --itn-dir thuduj12/fst_itn_zh --hotword /workspace/models/hotwords.txt > log.txt 2>&1
使用官方例子H5或Java客户端发起请求结果为：
<img width="1521" alt="image" src="https://github.com/user-attachments/assets/e11510f8-b729-4595-aaa8-acdd11012583">
### Expected behavior
预期结果：包含一句返回："is_final":true

**Comment by lyblsgo** [comment]
is_final字段是给实时用的，离线文件转写默认一段音频识别结果只有一次返回，客户端在发送完所有数据、接收到所有结果后会发起wb close请求，详细可参考 c++客户端
