### ISSUE TITLE
AssertionError: paraformer-zh-streaming is not registered

### ISSUE THREAD

**Issue by wangaolin1** [modelscope/FunASR#2057]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'python test.py'
2. See error

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.1.6):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.4.0):
 - How you installed funasr (source):
 - Python version:
 - GPU (e.g., RTX30680Ti
 - CUDA/cuDNN version (e.g., cuda11.8):
 - Any other relevant information:

**Comment by wuyuzhe** [comment]
AssertionError: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch is not registered

**Comment by yaleimeng** [comment]
pip升级modelscope版本可解决。
