### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by lsdlh** [modelscope/FunASR#2060]
from funasr import AutoModel

funasr_model = AutoModel(
            model="./models/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", 
            vad_model="./models/speech_fsmn_vad_zh-cn-16k-common-pytorch", 
            punc_model="./models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch",  
        )
response = funasr_model.generate(
    input='./6.wav',
    batch_size_s=300
)
print(response)

win11笔记本没有显卡，运行报错ValueError: math domain error
![image](https://github.com/user-attachments/assets/eb30e6e0-ef88-4232-afd8-2f3d8c913ef2)

speech_prob = math.log(sum_score)这里出现负数报错
音频文件 https://www.123pan.com/s/JnbTjv-U9leh

**Comment by LauraGPT** [comment]
Please list your envs.

**Comment by Lock1994** [comment]
did this issue solved？how to solve it?
