### ISSUE TITLE
音频开始有个类似开幕音，会被识别为“嗯”。这需要如何配置，还是需要微调

### ISSUE THREAD

**Issue by flystar8** [modelscope/FunASR#2061]
代码如下：
from funasr import AutoModel
from funasr.utils.postprocess_utils import rich_transcription_postprocess
import json

model_dir = "paraformer-zh"

model = AutoModel(
    model=model_dir,
    #vad_model="fsmn-vad", vad_model_revision="v2.0.4",
    vad_model="iic/speech_fsmn_vad_zh-cn-16k-common-pytorch",
    punc_model="ct-punc-c", punc_model_revision="v2.0.4",
    spk_model="cam++", spk_model_revision="v2.0.2",
    vad_kwargs={"max_single_segment_time": 30000},
    device="cpu",
)
input_file = 'fd34f7938f507baede3644a8cf16c31f.wav'
# zh
res = model.generate(
    input=input_file,
    cache={},
    language="auto", 
    use_itn=True,
    batch_size_s=60,
    merge_vad=True,  #
    merge_length_s=15,
    hotword=''
)

json_string = json.dumps(res, ensure_ascii=False)
print('res:%s' % json_string)

**Comment by LauraGPT** [comment]
finetune
