### ISSUE TITLE
funasr:funasr-runtime-sdk-gpu-0.1.1和funasr:funasr-runtime-sdk-gpu-0.1.0镜像怎么都下载不了了

### ISSUE THREAD

**Issue by lisong888** [modelscope/FunASR#2063]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by lyblsgo** [comment]
确认了镜像下载没问题，请check下网络或者docker分配的资源是否有问题
