### ISSUE TITLE
Paraformer-zh模型不加载VAD模型无法识别标点

### ISSUE THREAD

**Issue by SinlinLi** [modelscope/FunASR#2064]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

Paraformer-zh模型不加载VAD模型无法识别标点

### To Reproduce

因为我这边的业务已经先过一遍VAD了，所以ASR这边不需要开VAD。经过多次尝试之后发现如果不加载VAD模型，即使加载了PT也无法转录标点

#### Code sample

self.model = AutoModel(model=model_name, device=device, disable_update=True, punc_model="ct-punc")
### Environment

 - OS (e.g., Linux): Windows
 - FunASR Version (e.g., 1.0.0): 1.1.6
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Yeah. But it is not a bug.
