### ISSUE TITLE
热词和时间戳无法同时生效

### ISSUE THREAD

**Issue by buaibieshanghai** [modelscope/FunASR#2065]
环境：ubuntu下运行docker镜像 - funasr:funasr-runtime-sdk-cpu-0.4.5
运行命令：bash run_server.sh \ --download-model-dir /workspace/models \ --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-pytorch \ --model-dir damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 \ --punc-dir damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch \ --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \ --itn-dir thuduj12/fst_itn_zh \ --hotword /workspace/models/hotwords.txt

其中如果不指定--vad-dir ，热词生效，但是没有时间戳。
如果指定--vad-dir，热词失效。

有没有能够同时支持热词和时间戳的模型，还是我的使用方式错误？

**Comment by MyWestCity** [comment]
> 环境：ubuntu下运行docker镜像 - funasr:funasr-runtime-sdk-cpu-0.4.5 运行命令：bash run_server.sh \ --download-model-dir /workspace/models \ --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-pytorch \ --model-dir damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 \ --punc-dir damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch \ --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \ --itn-dir thuduj12/fst_itn_zh \ --hotword /workspace/models/hotwords.txt
> 
> 其中如果不指定--vad-dir ，热词生效，但是没有时间戳。 如果指定--vad-dir，热词失效。
> 
> 有没有能够同时支持热词和时间戳的模型，还是我的使用方式错误？

热词是否生效与vad有啥关系，想要时间戳和热词的可以用seaco_paraformer这个模型，但是这个模型转onnx默认是不带时间戳预测的，需要在转onnx的代码修改，具体可以看这个https://github.com/pika-online/funasr_seaco_paraformer_onnx_with_timestamp

**Comment by buaibieshanghai** [comment]
> > 环境：ubuntu下运行docker镜像 - funasr:funasr-runtime-sdk-cpu-0.4.5 运行命令：bash run_server.sh \ --download-model-dir /workspace/models \ --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-pytorch \ --model-dir damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 \ --punc-dir damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch \ --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \ --itn-dir thuduj12/fst_itn_zh \ --hotword /workspace/models/hotwords.txt
> > 其中如果不指定--vad-dir ，热词生效，但是没有时间戳。 如果指定--vad-dir，热词失效。
> > 有没有能够同时支持热词和时间戳的模型，还是我的使用方式错误？
> 
> 热词是否生效与vad有啥关系，想要时间戳和热词的可以用seaco_paraformer这个模型，但是这个模型转onnx默认是不带时间戳预测的，需要在转onnx的代码修改，具体可以看这个https://github.com/pika-online/funasr_seaco_paraformer_onnx_with_timestamp

好的，感谢答复，我去看一下

**Comment by MyWestCity** [comment]
> > > 环境：ubuntu下运行docker镜像 - funasr:funasr-runtime-sdk-cpu-0.4.5 运行命令：bash run_server.sh \ --download-model-dir /workspace/models \ --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-pytorch \ --model-dir damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 \ --punc-dir damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch \ --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \ --itn-dir thuduj12/fst_itn_zh \ --hotword /workspace/models/hotwords.txt
> > > 其中如果不指定--vad-dir ，热词生效，但是没有时间戳。 如果指定--vad-dir，热词失效。
> > > 有没有能够同时支持热词和时间戳的模型，还是我的使用方式错误？
> > 
> > 
> > 热词是否生效与vad有啥关系，想要时间戳和热词的可以用seaco_paraformer这个模型，但是这个模型转onnx默认是不带时间戳预测的，需要在转onnx的代码修改，具体可以看这个https://github.com/pika-online/funasr_seaco_paraformer_onnx_with_timestamp
> 
> 这个能使用docker直接指定吗，我试了一下，显示模型找不到

docker里面可能没有，我之前也是自己先拿pytorch的模型转的onnx，然后再到docker里面指定的model_dir，你给个地址给我，我可以把我转了之后的onnx的模型发给你，不过我这个在使用C++的onnx推理时要改一点代码，不然没法推理

**Comment by buaibieshanghai** [comment]
> > > > 环境：ubuntu下运行docker镜像 - funasr:funasr-runtime-sdk-cpu-0.4.5 运行命令：bash run_server.sh \ --download-model-dir /workspace/models \ --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-pytorch \ --model-dir damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 \ --punc-dir damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch \ --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \ --itn-dir thuduj12/fst_itn_zh \ --hotword /workspace/models/hotwords.txt
> > > > 其中如果不指定--vad-dir ，热词生效，但是没有时间戳。 如果指定--vad-dir，热词失效。
> > > > 有没有能够同时支持热词和时间戳的模型，还是我的使用方式错误？
> > > 
> > > 
> > > 热词是否生效与vad有啥关系，想要时间戳和热词的可以用seaco_paraformer这个模型，但是这个模型转onnx默认是不带时间戳预测的，需要在转onnx的代码修改，具体可以看这个https://github.com/pika-online/funasr_seaco_paraformer_onnx_with_timestamp
> > 
> > 
> > 这个能使用docker直接指定吗，我试了一下，显示模型找不到
> 
> docker里面可能没有，我之前也是自己先拿pytorch的模型转的onnx，然后再到docker里面指定的model_dir，你给个地址给我，我可以把我转了之后的onnx的模型发给你，不过我这个在使用C++的onnx推理时要改一点代码，不然没法推理

好的，感谢，那你加我VX吧，17370109094

**Comment by see-you-at-Zihuatanejo** [comment]
> > > > 环境：ubuntu下运行docker镜像 - funasr:funasr-runtime-sdk-cpu-0.4.5 运行命令：bash run_server.sh \ --download-model-dir /workspace/models \ --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-pytorch \ --model-dir damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 \ --punc-dir damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch \ --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \ --itn-dir thuduj12/fst_itn_zh \ --hotword /workspace/models/hotwords.txt
> > > > 其中如果不指定--vad-dir ，热词生效，但是没有时间戳。 如果指定--vad-dir，热词失效。
> > > > 有没有能够同时支持热词和时间戳的模型，还是我的使用方式错误？
> > > 
> > > 
> > > 热词是否生效与vad有啥关系，想要时间戳和热词的可以用seaco_paraformer这个模型，但是这个模型转onnx默认是不带时间戳预测的，需要在转onnx的代码修改，具体可以看这个https://github.com/pika-online/funasr_seaco_paraformer_onnx_with_timestamp
> > 
> > 
> > 这个能使用docker直接指定吗，我试了一下，显示模型找不到
> 
> docker里面可能没有，我之前也是自己先拿pytorch的模型转的onnx，然后再到docker里面指定的model_dir，你给个地址给我，我可以把我转了之后的onnx的模型发给你，不过我这个在使用C++的onnx推理时要改一点代码，不然没法推理

请问C++的推理代码您是怎么修改的

**Comment by LauraGPT** [comment]
选择时间戳模型，就是既可以支持时间戳，又可以支持时间错。

**Comment by lyblsgo** [comment]
nohup bash run_server.sh \
  --download-model-dir /workspace/models \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --model-dir damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
  --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
  --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
  --itn-dir thuduj12/fst_itn_zh \
  --hotword /workspace/models/hotwords.txt > log.txt 2>&1 &
加载时间戳模型 和 lm，同时支持时间戳和热词
