### ISSUE TITLE
下载funasr:funasr-runtime-sdk-gpu-0.1.1，下到一半提示这个是什么问题

### ISSUE THREAD

**Issue by lisong888** [modelscope/FunASR#2066]
下载funasr:funasr-runtime-sdk-gpu-0.1.1，下到一半提示这个是什么问题，重复pull很多次都这样
![1725615262356](https://github.com/user-attachments/assets/21b070d6-6fb4-4578-b78d-7a0b65560b5a)

**Comment by lyblsgo** [comment]
确认了镜像下载没问题，请check下网络或者docker分配的资源是否有问题
