### ISSUE TITLE
可以区分说话人角色和数量

### ISSUE THREAD

**Issue by ybshaw** [modelscope/FunASR#2067]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help
在推理时，可以指定说话人角色以及个数吗，比如限制识别结果中只有两个角色，类似这种 1：用户 2：客服

**Comment by LauraGPT** [comment]
Not yet.

**Comment by HTWMedia** [comment]
有说话人区分的在线API需要吗，
![角色区分](https://github.com/user-attachments/assets/afe9e6a9-f99b-4138-b402-83440a59b795)
类似这样，识别并区分说话人，可并发。
