### ISSUE TITLE
有多人说话场景分离的模型吗？

### ISSUE THREAD

**Issue by MonolithFoundation** [modelscope/FunASR#2072]
之前有个MFCCA但是最新的modelscope加载不了

**Comment by HTWMedia** [comment]
有说话人区分的在线API需要吗，
![角色区分](https://github.com/user-attachments/assets/f530a97f-56f6-4e24-84b0-64f6fbffb51c)
，类似这样的语音识别，并区分说话人，可并发。

**Comment by LauraGPT** [comment]
MFCCA is not supported. You could ref to https://github.com/modelscope/FunASR?tab=readme-ov-file#paraformer. add `spk_model='cam++'`

**Comment by newbie521** [comment]
> 之前有个MFCCA但是最新的modelscope加载不了

您好，我想问一下您有找到多人说话分离的吗，我也想了解一下

**Comment by king121456** [comment]
给你贴段代码吧
`from funasr import AutoModel
from typing import List, Dict
import json


def format_recognition_result(res: List[Dict]) -> str:
    """格式化语音识别结果"""
    formatted_output = []

    for result in res:
        # 获取句子级别的信息
        sentences = result["sentence_info"]

        formatted_output.append("语音识别结果：\n")
        for sentence in sentences:
            speaker_id = sentence["spk"]
            text = sentence["text"]
            start_time = sentence["start"] / 1000  # 转换为秒
            end_time = sentence["end"] / 1000

            # 格式化时间戳和文本
            formatted_sentence = (
                f"说话人 {speaker_id} "
                f"[{start_time:.2f}s - {end_time:.2f}s]: "
                f"{text}"
            )
            formatted_output.append(formatted_sentence)

    return "\n".join(formatted_output)


# 初始化模型
model = AutoModel(
    model="paraformer-zh", vad_model="fsmn-vad", punc_model="ct-punc", spk_model="cam++"
)

# 生成识别结果
res = model.generate(
    input="test.m4a",
    batch_size_s=300,
    hotword="魔搭",
)

# 打印格式化后的结果
print(format_recognition_result(res))
`
最后输出的结果是：
![image](https://github.com/user-attachments/assets/72741445-e28c-4600-b54d-3de40afe170b)

**Comment by newbie521** [comment]
> 给你贴段代码吧 ` from funasr import AutoModel from typing import List, Dict import json
> 
> def format_recognition_result(res: List[Dict]) -> str:
> 
> ```
> formatted_output = []
> 
> for result in res:
>     sentences = result["sentence_info"]
> 
>     formatted_output.append("语音识别结果：\n")
>     for sentence in sentences:
>         speaker_id = sentence["spk"]
>         text = sentence["text"]
>         start_time = sentence["start"] / 1000 
>         end_time = sentence["end"] / 1000
> 
>         formatted_sentence = (
>             f"说话人 {speaker_id} "
>             f"[{start_time:.2f}s - {end_time:.2f}s]: "
>             f"{text}"
>         )
>         formatted_output.append(formatted_sentence)
> 
> return "\n".join(formatted_output)
> ```
> 
> model = AutoModel( model="paraformer-zh", vad_model="fsmn-vad", punc_model="ct-punc", spk_model="cam++" )
> 
> res = model.generate( input="test.m4a", batch_size_s=300, hotword="魔搭", )
> 
> print(format_recognition_result(res))
> 
> ` 最后输出的结果是： ![image](https://private-user-images.githubusercontent.com/16264889/401074044-72741445-e28c-4600-b54d-3de40afe170b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMjc5NDQsIm5iZiI6MTczNjMyNzY0NCwicGF0aCI6Ii8xNjI2NDg4OS80MDEwNzQwNDQtNzI3NDE0NDUtZTI4Yy00NjAwLWI1NGQtM2RlNDBhZmUxNzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDA5MTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NzgyNGE5MTNiMTgzNTc4MDI1ZjRhMmVlNTIyNWYyMzRlODg0NDQ4MWIyOTU3MjJhZTY0MjcyODQ4MzNhZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RRJ6Ebyb3LsqpWLlbLbYiRKPM0_9hSvCcUND3gR4zEw)

我可能没有表述清楚，我的意思是说想要分离同一时间多人说话，而不是按顺序说话的多人，不好意思，可能是我表达不够清楚

**Comment by MonolithFoundation** [comment]
同问

**Comment by gongc1234** [comment]
> 给你贴段代码吧 ` from funasr import AutoModel from typing import List, Dict import json
> 
> def format_recognition_result(res: List[Dict]) -> str:
> 
> ```
> formatted_output = []
> 
> for result in res:
>     sentences = result["sentence_info"]
> 
>     formatted_output.append("语音识别结果：\n")
>     for sentence in sentences:
>         speaker_id = sentence["spk"]
>         text = sentence["text"]
>         start_time = sentence["start"] / 1000 
>         end_time = sentence["end"] / 1000
> 
>         formatted_sentence = (
>             f"说话人 {speaker_id} "
>             f"[{start_time:.2f}s - {end_time:.2f}s]: "
>             f"{text}"
>         )
>         formatted_output.append(formatted_sentence)
> 
> return "\n".join(formatted_output)
> ```
> 
> model = AutoModel( model="paraformer-zh", vad_model="fsmn-vad", punc_model="ct-punc", spk_model="cam++" )
> 
> res = model.generate( input="test.m4a", batch_size_s=300, hotword="魔搭", )
> 
> print(format_recognition_result(res))
> 
> ` 最后输出的结果是： ![image](https://github.com/user-attachments/assets/72741445-e28c-4600-b54d-3de40afe170b)

有没有试过，超过30分钟的音频，会分离出一些奇怪的其他人，效果有点不准了？

**Comment by dididiskq** [comment]
> 给你贴段代码吧 ` from funasr import AutoModel from typing import List, Dict import json
> 
> def format_recognition_result(res: List[Dict]) -> str:
> 
> ```
> formatted_output = []
> 
> for result in res:
>     sentences = result["sentence_info"]
> 
>     formatted_output.append("语音识别结果：\n")
>     for sentence in sentences:
>         speaker_id = sentence["spk"]
>         text = sentence["text"]
>         start_time = sentence["start"] / 1000 
>         end_time = sentence["end"] / 1000
> 
>         formatted_sentence = (
>             f"说话人 {speaker_id} "
>             f"[{start_time:.2f}s - {end_time:.2f}s]: "
>             f"{text}"
>         )
>         formatted_output.append(formatted_sentence)
> 
> return "\n".join(formatted_output)
> ```
> 
> model = AutoModel( model="paraformer-zh", vad_model="fsmn-vad", punc_model="ct-punc", spk_model="cam++" )
> 
> res = model.generate( input="test.m4a", batch_size_s=300, hotword="魔搭", )
> 
> print(format_recognition_result(res))
> 
> ` 最后输出的结果是： ![image](https://github.com/user-attachments/assets/72741445-e28c-4600-b54d-3de40afe170b)

大佬你好，为什么我识别到的全是一个说话人，那里的问题，求解答
语音识别结果：

说话人 0 [1.02s - 2.40s]: 你混蛋说什么，
说话人 0 [2.40s - 3.86s]: 我从嫁给你就没落着什么，
说话人 0 [3.86s - 4.84s]: 你想让我说什么，
说话人 0 [4.84s - 6.24s]: 天天天就知道玩这个钱，
说话人 0 [6.24s - 8.96s]: 是你当时给我干完回家就当打放什么私房钱了，
说话人 0 [8.96s - 10.04s]: 板布洗地不拖，
说话人 0 [10.28s - 11.68s]: 换个拖鞋就坐在电脑前，
说话人 0 [11.68s - 12.22s]: 是这事儿，
说话人 0 [12.22s - 14.02s]: 就是那事儿烦死了，
说话人 0 [14.14s - 15.26s]: 都现在的说什么呢？
说话人 0 [15.26s - 17.18s]: 你还学会人家藏私房钱了，
说话人 0 [17.18s - 18.14s]: 你自己疑心病，
说话人 0 [18.14s - 20.52s]: 晚期家庭闲钱让你藏吗？
说话人 0 [20.52s - 21.08s]: 烦死吧，
说话人 0 [21.12s - 22.72s]: 你天天烦死了。
说话人 0 [22.72s - 23.98s]: 你挣的那俩钢蹦不行，
说话人 0 [23.98s - 25.22s]: 你你还得着藏吗？
说话人 0 [25.66s - 26.24s]: 妈的，
说话人 0 [26.60s - 27.02s]: 不过。
