### ISSUE TITLE
实时语音听写服务后续会考虑支持时间戳吗

### ISSUE THREAD

**Issue by johnshawn-david** [modelscope/FunASR#2076]
现在离线文件转写服务支持时间戳，在使用2pass模式时，只会在一句话结束的时候返回时间戳，在实时听写的时候会返回文字，但不会返回时间戳，后续会考虑在实时文字返回的时候带上时间戳吗

**Comment by LauraGPT** [comment]
You could develop it yourself. Ref to cif code.
