### ISSUE TITLE
如果要训练一个中文标点检测模型，那么数据的准备格式是怎样的呢？

### ISSUE THREAD

**Issue by wanganddi0918** [modelscope/FunASR#2086]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. search the issues.
2. search the docs.

#### What is your question 
如果要训练一个中文标点检测模型，那么数据的准备格式是怎样的呢？论文中提出使用 BIO 的方法进行数据标注，但是我在 data 文件夹中没有找到对应的样例呀

**Comment by wanganddi0918** [comment]
此外，可不可以发布一个标点模型微调的例子呢？貌似 #893 中的内容并没有 merge 到 master 分支中，其中的部分文件（例如 tokens.txt 和 puncs.txt）也没有全部给出呀？

**Comment by LauraGPT** [comment]
Not support. Actually, it is not necessary now. The new model, `SenseVoice` and `whisper` contain the puncs.
