### ISSUE TITLE
RuntimeError: mixed dtype (CPU): expect parameter to have scalar type of Float

### ISSUE THREAD

**Issue by icestoneking** [modelscope/FunASR#2092]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. 训练bf16模型，推理的速度变慢，应该是转会fp32推理的，在配置文件里添加参数：
     bf16:True
     之后报错：RuntimeError: mixed dtype (CPU): expect parameter to have scalar type of Float

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.5.0):
 - ModelScope Version (e.g., 2.4.0):
 - PyTorch Version (e.g., 2.3.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., GeForce RTX3060，12G)
 - CUDA/cuDNN version (e.g., cuda12.1):

 - Any other relevant information:

**Comment by LauraGPT** [comment]
You could train bf16 model with deepspeed.
