### ISSUE TITLE
websocket service cannot do real-time recognition after deployment with docker

### ISSUE THREAD

**Issue by ruifengma** [modelscope/FunASR#2093]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. search the issues.
2. search the docs.

#### Code

```
nohup bash run_server.sh \
  --download-model-dir /workspace/models \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
  --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
  --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
  --itn-dir thuduj12/fst_itn_zh \
  --hotword /workspace/models/hotwords.txt \
  --certfile 0 > log.txt 2>&1 &
```

#### What have you tried?
I have deploy funasr successfully and tested with the client which can be used for audio recognition, but when I use the example html (index.html) and tried to connect my service, it cannot really react as real time recognition, but only reply me after I click the stop button (which is not the same as the demo from official website)

#### What's your environment?

 - OS (e.g., Linux):CentOS 7
 - FunASR Version (e.g., 1.0.0): from docker
 - ModelScope Version (e.g., 1.11.0): from docker
 - PyTorch Version (e.g., 2.0.0): from docker
 - How you installed funasr (`pip`, source): no
 - Python version: from docker
 - GPU (e.g., V100M32) from docker
 - CUDA/cuDNN version (e.g., cuda11.7): no
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1) **funasr-runtime-sdk-cpu-0.4.5**
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Sorry, the realtime service does not support English so far. We would support it soon.

**Comment by ruifengma** [comment]
> Sorry, the realtime service does not support English so far. We would support it soon.

Thanks for the reply, is Chinese supported by realtime websocket service? How could I specify the parameter? Thanks
