### ISSUE TITLE
运行funasr-wss-server: error while loading shared libraries: libtorch_global_deps.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joewale** [modelscope/FunASR#2095]
使用镜像 registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-gpu-0.1.1

**Comment by miguellords** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by joewale** [comment]
我的是linux系统

**Comment by lyblsgo** [comment]
参考文档部署 https://github.com/modelscope/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_gpu_zh.md

**Comment by pdxrlj** [comment]
怎么解决的，我也有相同的问题，运行run_server_2pass.sh ，是不支持2pass在gpu上吗
