### ISSUE TITLE
微调SenseVoiceSmall时发现每轮cv的acc均为0

### ISSUE THREAD

**Issue by czl66** [modelscope/FunASR#2100]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

如题，我在尝试用aishell2微调SenseVoiceSmall时，观察log发现每轮训练结束后进行的cv的acc均为0;
排查得知，SenseVoiceSmall类里的forward方法返回的stats里少了“acc”的key，导致cv的acc一致为初始值0，从而影响checkpoint的保存。
<img width="652" alt="截屏2024-09-21 16 03 14" src="https://github.com/user-attachments/assets/8d440369-a072-4d87-bdf0-9227ef57219f">
希望官方更新一下，然后我用pip再install一下funasr。谢谢🙏！

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run bash finetune.sh（SenseVoice repo）

**Comment by Aiolei** [comment]
找不到val的acc，这样无法判定保存模型，请问楼主解决了吗

**Comment by Jzone-solo-Legend** [comment]
> 找不到val的acc，这样无法判定保存模型，请问楼主解决了吗

我最后是使用loss来作为标准去保存ckpt的
