### ISSUE TITLE
有大佬能帮我解释一下为什么同样的音频识别多次每次的结果都有差异吗

### ISSUE THREAD

**Issue by HHUhujiaxin** [modelscope/FunASR#2111]
有大佬能帮我解释一下为什么同样的音频识别多次每次的结果都有差异吗

**Comment by lhanzl** [comment]
请问你说的是python的推理还是C++ runtime？我遇到过funasr1.0之前的python推理出现你讲的问题，当时发现似乎跟wav.scp中的音频顺序有关系，不知道为什么。

**Comment by LauraGPT** [comment]
音频特征哪里有随机噪声扰动，如果音频是静音，或者声音比较小，就会遇到你说的这个情况
