### ISSUE TITLE
Which romanization Persian model use

### ISSUE THREAD

**Issue by nshmyrev** [modelscope/FunASR#2117]
Hello

Persian model https://modelscope.cn/models/iic/speech_UniASR_asr_2pass-fa-16k-common-vocab1257-pytorch-online/ version 1.0.1 uses some kind of roman letters in the output. It is not clear how to turn them back to unicode. Please suggest.

Older version 1.0.0 uses unicode but not compatible with latest funasr.

**Comment by LauraGPT** [comment]
Sorry, we would not maintain all of `UniASR` models any more.
