### ISSUE TITLE
如何让VAD对静音段更敏感？

### ISSUE THREAD

**Issue by TinaChen95** [modelscope/FunASR#2126]
说话人语速较快、停顿较短的时候，如何配置VAD参数，才能让切割出来的音频片段不要过长？
使用默认参数时，总是出现语音片段硬截断的情况，不希望这样的情况出现，该怎么办呢？

**Comment by LauraGPT** [comment]
模型介绍里面有：https://www.modelscope.cn/models/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch
