### ISSUE TITLE
实时语音识别出错

### ISSUE THREAD

**Issue by goddamnVincent** [modelscope/FunASR#2127]
![屏幕截图 2024-10-09 135552](https://github.com/user-attachments/assets/d5fa3ffa-992f-4871-ab0d-6759ba7b0f7f)
使用**官方示例**进行实时语音识别推理时候出现问题，
当使用自己的wav文件输入之后，输出错误结果，如图所示。

请问这是什么问题？

**Comment by LauraGPT** [comment]
请按照模板提issue

**Comment by gsc1456** [comment]
你用soxi命令看看。wav文件的采集率是否一样

**Comment by yangkkk233** [comment]
我也会出现这种问题，使用16000hz的文件就能正常识别，但是自己的音频文件是44100hz，就会出现不正确的结果

**Comment by goddamnVincent** [comment]
已经解决

**Comment by bigeyefish** [comment]
请问这个问题解决了吗，我也遇到了，使用的是最新代码

**Comment by goddamnVincent** [comment]
> 请问这个问题解决了吗，我也遇到了，使用的是最新代码

解决了

**Comment by Guolipeng666** [comment]
怎么解决的，可以说下吗
