### ISSUE TITLE
python websocket实时语音识别推理速度越来越慢

### ISSUE THREAD

**Issue by secslim** [modelscope/FunASR#2136]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help
使用官网提供的python websocket脚本启动了一个服务，客户端访问超过两个小时之后，识别速度变得越来越慢，有大佬遇到过这个问题吗？

**Comment by LauraGPT** [comment]
Python version is just a demo. You could use the docker service.
