### ISSUE TITLE
onnxruntime 报错 CL.exe 退出

### ISSUE THREAD

**Issue by yjyccm** [modelscope/FunASR#2147]
Release版本报错，Debug编译不会报错

严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	MSB6006	“CL.exe”已退出，代码为 -1073740791。	funasr	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	755

**Comment by OnlyDelusion** [comment]
我已经解决了这个问题，有相同问题的人 参考我的改法吧，我也是找了很久。debug可以编译，release报错，对比了设置差距后  定位到了一个选项组合可以解决此问题。
右键funasr属性，打开属性页面，选择C++->优化->最大化速度修改为 禁用，内联函数扩展修改为已禁用 再编译即可。  我的已经编译过了，如果你的也是debug正常release异常，修改后也无效 就再去对比一下其他选项。 主要应该是《C++->优化->最大化速度修改为 禁用》
