### ISSUE TITLE
模型 model.py 推理 函数默认参数被修改

### ISSUE THREAD

**Issue by zhuqn** [modelscope/FunASR#2149]
https://github.com/modelscope/FunASR/blob/98e2c546a08917f450d32d63968affd5b975ad2a/funasr/models/fsmn_vad_streaming/model.py#L648

![问题](https://github.com/user-attachments/assets/d3e5feef-9113-4b4a-9a78-4f665236fc07)

fsmn_vad中的推理调用一次之后，函数的默认参数就会被改掉，这个是故意设置成这样的？比如cache，从框架代码auto_model.py推理传参是没有的，推理后直接把model.py 中 inference函数的默认参数 cache: dict = {},给改掉了

**Comment by goddamnVincent** [comment]
这是缓存，每次用完都会清掉的
