### ISSUE TITLE
SenseVoice标点符号，funasr缺失sentence等

### ISSUE THREAD

**Issue by zhouhuirun2015** [modelscope/FunASR#2153]
issue已搜索，未找到相关提问

问题：
1. funasr从0.7升级到最新版之后，输出的sentence没有了，新版本输出改了吗，有办法获取吗；
2. 非中英的东南亚小语种用哪个标点符号模型呢；
3. senseVoice要想有sentence、标点符号该如何配置pipeline呢；

谢谢

**Comment by LauraGPT** [comment]
1. https://github.com/modelscope/FunASR/blob/main/examples/industrial_data_pretraining/paraformer/demo.py
2. no
3. no
