### ISSUE TITLE
情感分类unknown类别判定策略

### ISSUE THREAD

**Issue by WangFeiji0928** [modelscope/FunASR#2155]
#### What is your question?
训练集明显不会有unknown这一类，但是推理结果可以有unknown，而且禁用unknown这一类别之后，其他类别的logits不会受影响
，ctc_logits是根据什么分配给unknown这一类别的呢？

**Comment by LauraGPT** [comment]
source code is all you need.

**Comment by WangFeiji0928** [comment]
Fine...Anyway milion thanks
