### ISSUE TITLE
实时识别语音，2pass模式，一句话识别出来太细碎，不能成句

### ISSUE THREAD

**Issue by gsc1456** [modelscope/FunASR#2160]
如题，这个问题困扰了我很久，请问要做什么配置吗？自定义客户端。
我的第一句话：明 明 是 第 一 台 产 品
第二句话：小 米 为 什 么 定 位 su7
第三句话：而 不 是 su1 呢
![image](https://github.com/user-attachments/assets/9bd59ca1-cecb-4f5d-b998-1cae73f9b933)

**Comment by LauraGPT** [comment]
你可以自己配置，chunk_size参数
