### ISSUE TITLE
请问微调后的模型，如何计算字错率？

### ISSUE THREAD

**Issue by lukeewin** [modelscope/FunASR#2163]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. search the issues. 
yes
3. search the docs.
yes

#### What is your question?
微调后的paraformerm实时语音识别模型，如何计算它的字错率？

#### What's your environment?

 - OS (e.g., Linux): Linux
 - FunASR Version (e.g., 1.0.0):  1.1.12
 - ModelScope Version (e.g., 1.11.0): 1.19.0
 - PyTorch Version (e.g., 2.0.0): 2.1.2+cu118
 - How you installed funasr (`pip`, source): pip
 - Python version: 3.8
 - GPU (e.g., V100M32) 2*RTX 4090
 - CUDA/cuDNN version (e.g., cuda11.7): cuda 11.8
 - Any other relevant information: iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online

**Comment by LauraGPT** [comment]
ref to aishell/paraformer/run.sh `stage5`
