### ISSUE TITLE
能否微调成一个分类任务，target为每条语音的分类标签

### ISSUE THREAD

**Issue by chaunceyliu30** [modelscope/FunASR#2166]
#### What is your question?
想请教一下如果做语音分类任务，是否在准备数据集时将target变为分类标签即可，不知道这样会不会造成模型性能比较大的损失

#### Code
DNA

#### What have you tried?
查看了文档发现没有微调分类任务对应的教程，或者模型能否使用transformers加载呢？

#### What's your environment?
DO NOT RELATED

**Comment by LauraGPT** [comment]
details.
