### ISSUE TITLE
fsmn-vad 模型似乎有 CPU 性能问题

### ISSUE THREAD

**Issue by hongfanmeng** [modelscope/FunASR#2168]
#### What is your question?

fsmn-vad 模型推理有 CPU 性能问题，当推理较长的音视频时 CPU 会满载，而且似乎只使用了单线程

#### Code

```py
from funasr import AutoModel

model_vad = AutoModel(model="fsmn-vad", device="cuda:0")
res = model_vad.generate(input='vad_example.wav')
```

#### What have you tried?

以上代码在视频较长时会占用 CPU 100% 负载，而且没有多线程优化，使用较低主频的服务器 CPU 时会十分慢

#### What's your environment?

 - OS: Linux
 - FunASR Version: 1.1.12
 - ModelScope Version: 1.19.0
 - PyTorch Version: 2.5.0
 - How you installed funasr: pip
 - Python version:
 - GPU: RTX3090
 - CUDA/cuDNN version: cuda12.4

**Comment by LauraGPT** [comment]
vad模型里面，nn计算占比非常小，绝大部分是cpu任务。python多线程，意义不大

**Comment by lyfuci** [comment]
@hongfanmeng 所以这个有解决吗，我现在是发现，开发机器 windows+conda好像能用到CPU的多线程(只是根据逻辑CPU的运行情况判断)，但是线上环境 container(fedora)，一直都是单线程运行。有办法CPU并行吗。

**Comment by hongfanmeng** [comment]
fsmn-vad 的内部逻辑用了一个 dict 当 cache，不太好改成并行的

**Comment by lyfuci** [comment]
> fsmn-vad 的内部逻辑用了一个 dict 当 cache，不太好改成并行的

感谢大佬，哈哈哈。不过还挺绝望的，这边服务器上的CPU性能都很低。没有GPU基本上比较难用了。

**Comment by yeyunu** [comment]
@LauraGPT 所以完全没有优化推理速度的手段了吗

**Comment by RobertLiu0905** [comment]
改成多进程就能多CPU去算fbank了
