### ISSUE TITLE
seaco语音模型微调报错：'NoneType' object has no attribute 'contiguous'

### ISSUE THREAD

**Issue by smengfei** [modelscope/FunASR#2178]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug
从git上拉取的FunASR框架，运行seaco模型微调时报错'NoneType' object has no attribute 'contiguous'，排查代码发现AudioDatasetHotword对象的初始化方法中给定的seaco_id参数默认值是seaco_id: bool = 0，造成后面collator函数中生成的seaco_label_pad是None，从而引发'NoneType' object has no attribute 'contiguous'，目前我在seaco_paraformer包下的finetune.sh脚本中增加了++dataset.seaco_id=true参数用于修改seaco_id的默认值为True，模型微调可以正常运行，但我不知道这么改是否会对模型的训练效果有影响

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.1.12):
 - ModelScope Version (e.g., 1.18.1):
 - PyTorch Version (e.g., 2.3.1):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda12.1):
 - Any other relevant information:

**Comment by R1ckShi** [comment]
dataset的这个配置在config文件里面
<img width="290" alt="image" src="https://github.com/user-attachments/assets/9065f4c3-d123-42fe-8589-ecb4e4b11442">
不知道是不是哪次更新导致的bug，可以先确认下你的config文件

**Comment by smengfei** [comment]
<img width="358" alt="image" src="https://github.com/user-attachments/assets/f902c1f8-5e28-4102-b153-8493cf3aeb3b">
最新下载的模型配置

**Comment by smengfei** [comment]
我用这段代码下载的
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/5be66b8d-e8be-48b6-bc0d-41445dcee771">

**Comment by R1ckShi** [comment]
把model revision去掉重新拉一下试试

**Comment by lxp3** [comment]
@smengfei 可能是由于版本导致的。
Funasr 旧的finetune.sh脚本缺少指定命令行参数，如指定热词数据集 ++dataset="AudioDatasetHotword"。从你的截图来看，它用的是AudioDataset，导致它的返回对象缺少了字段 {"seaco_id": self.seaco_id}。

换成最新的finetune.sh脚本，应该可以解决seaco_id为None的错误。
