### ISSUE TITLE
为什么我的识别结果格式和平台在线的不一样，求好心人告知

### ISSUE THREAD

**Issue by ordinary-lv** [modelscope/FunASR#2179]
![微信图片_20241029100926](https://github.com/user-attachments/assets/901d3416-0ef0-45c8-97f6-b08bee15e8c2)
wo我想要这种格式的识别结果，可我用平台的源码html测试却是纯文本没有时间戳和换行？？？
![微信图片_20241029100940](https://github.com/user-attachments/assets/efb57d7a-92d9-4eca-b905-bb413797d84c)
求大佬告知，我是前端开发纯小白

**Comment by LauraGPT** [comment]
切换时间戳模型就可以了
