### ISSUE TITLE
请问，像那种专业词汇量大的场景下，推荐使用funasr么？使用语言模型，目前微调不了么？

### ISSUE THREAD

**Issue by qqqq640** [modelscope/FunASR#2251]
专业词汇量比较大，大部分人名地名无法识别，微调和使用热词后相对改善一些，但是专业词汇太多，超过热词推荐数量后，效果恶化。请问现在想挂载语言模型，语言模型微调目前使用不了么？ 像这种情况有什么合适的实现方案么？感谢指导！

**Comment by LauraGPT** [comment]
docker部署里面的ngram可以微调。

**Comment by qqqq640** [comment]
好的谢谢

**Comment by qqqq640** [comment]
请问有操作文档之类的么？非常感谢！

**Comment by qqqq640** [comment]
找到了，非常感谢

**Comment by wwfcnu** [comment]
> 找到了，非常感谢

请问文档的具体路径是什么呢，可以发一下吗

**Comment by Chun-J1** [comment]
> > 找到了，非常感谢
> 
> 请问文档的具体路径是什么呢，可以发一下吗

我也没看到到底在哪
