### ISSUE TITLE
运行Whisper-large-v3出现bug：UnboundLocalError: cannot access local variable 'get_tokenizer' where it is not associated with a value

### ISSUE THREAD

**Issue by user2311717757** [modelscope/FunASR#2259]
我的运行脚本：
from funasr import AutoModel

model="iic/Whisper-large-v3"
model = AutoModel(
    model=model,  
    vad_model="fsmn-vad",  
    vad_kwargs={"max_single_segment_time": 90000}, 
    # spk_model="cam++", 
    )
res = model.generate(input="left.wav", 
                     batch_size_s=300, 
                     hotword='魔搭')
print(res)

**Comment by user2311717757** [comment]
已解决

**Comment by nilin1998** [comment]
> 已解决

请问是怎么解决的呢
