### ISSUE TITLE
rk3588部署，模型的转换rknn

### ISSUE THREAD

**Issue by happywch** [modelscope/FunASR#2286]
我希望在香橙派rk3588上部署funasr，但是这需要将模型使用rknn-toolkit2转化为rknn。想要知道paraformer-zh-streaming ，ct-punc ，fsmn-vad 这些模型的输入形状。还有部署的可能性

**Comment by baichuan1997** [comment]
rk3588使用fsmn-vad推理加速遇到同样问题，两个问题：
1.转换RKNN模型的时候，输入形状不知道多少；
2.转换完的模型貌似funasr不支持rknn模型加载，怎么加载rknn呢。
可以和楼主沟通一下吗，互相沟通一下思路。

**Comment by ggbsaber** [comment]
请问大佬最后解决了吗能否提供一下思路

**Comment by lqx-all** [comment]
> 我希望在香橙派rk3588上部署funasr，但是这需要将模型使用rknn-toolkit2转化为rknn。想要知道paraformer-zh-streaming ，ct-punc ，fsmn-vad 这些模型的输入形状。还有部署的可能性

大佬解决了吗 这个动态输入怎么解决的呢

**Comment by lpu-bash** [comment]
大佬们遇到过这个问题吗“ValueError: The input 0 of NonZero('/NonZero') need to be constant! It will cause the graph to be a dynamic graph!“

**Comment by yowrhihoil** [comment]
请问大佬解决了吗，我也遇到同样的问题。

**Comment by lpu-bash** [comment]
没有，没解决









在 2026-04-21 15:18:54，"yowrhihoil" ***@***.***> 写道：

yowrhihoil left a comment (modelscope/FunASR#2286)

请问大佬解决了吗，我也遇到同样的问题。
