### ISSUE TITLE
What is the meaning of this? 

### ISSUE THREAD

**Issue by tshmak** [modelscope/FunASR#2321]
What is the reason behind [this line of code](https://github.com/modelscope/FunASR/blob/f921a7181855a356237667200330001597b2473a/funasr/auto/auto_model.py#L176)? 

Why are we restricting `download_model` to the case when `model_conf` is not in `kwargs`? 

Cos I have a situation where I want to specify `++model_conf` when running the script in a model where `model_conf` was not defined, but it led to a different outcome because of this line. (In fact it was an error, because my model was defined in `remote_code`, and without `download_model`, it says my model is not registered.

**Comment by LauraGPT** [comment]
Please show me your full code.

**Comment by tshmak** [comment]
I've defined my own model using `remote_code` and it's not very convenient to share. Would it be possible to explain the purpose of the above line without my codes?

**Comment by LauraGPT** [comment]
I mean that, you could show the code how to use it. Not your model itself.
I thank you could set the parameters via `config.yaml`.

**Comment by LauraGPT** [comment]
Any parameter could be set via:
1. `config.yaml`
2. 'configuration.json'
3. shell recipe via `++x.x=value`

If you set the same parameter via above all method at the same time, the priority: 1<2<3.
The`model_conf` is not suggested to set via `3` method.
