### ISSUE TITLE
data2vec_pretrain 

### ISSUE THREAD

**Issue by locasxe** [modelscope/FunASR#775]
OS: linux
Python/C++ Version：3.8
Package Version：pytorch 2.0.1、torchaudio 2.0.2、modelscope 1.7.1、funasr version 0.6.9
Model：aishell2/pretrain
Command：bash run.sh
Error log：AttributeError: 'TriStageLR' object has no attribute '_step_count'

Have any idea?

**Comment by jmwang66** [comment]
Please provide the complete log
