### ISSUE TITLE
客户端python执行推理音频卡住

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [modelscope/FunASR#879]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87591236/640b0898-4304-4da2-8de4-c60900a9e3ea)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87591236/1f382bc5-84c9-40ce-87e8-3aca82839b5b)
以下是执行测试案例中的音频运行效果
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87591236/c399b928-837f-41e8-89ce-d9eea30888ba)

**Comment by lyblsgo** [comment]
If possible, please upload your audio file so that I can see if I can reproduce it

**Comment by kli017** [comment]
@HaSaKiYasuooo 打扰了，请问日志文件路径是什么啊
