### ISSUE TITLE
How to decode Lora finetune model

### ISSUE THREAD

**Issue by lhanzl** [modelscope/FunASR#934]
ubuntu20.04, funasr&modelscope is last version.
Lora finetune model can not decode:

RuntimeError：AutomaticSpeechRecognitionPipeline：Error（s）in loading state_dict for Paraformer：
   unexpected key(s) in state_dict: "encoder.encoders0.0.self_attn.linear_q_k_v.lora_A"

**Comment by hnluo** [comment]
Please list your envs:

Package Version：funasr version（pip list）
Model：
Command：
Details：
Error log：

**Comment by lhanzl** [comment]
Package Version：0.7.6
Model：Lora finetuned speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch model
Command：python infer.py
Details：when inference lora  finetuned speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch model
Error log：
RuntimeError：AutomaticSpeechRecognitionPipeline：Error（s）in loading state_dict for Paraformer：
unexpected key(s) in state_dict: "encoder.encoders0.0.self_attn.linear_q_k_v.lora_A"

**Comment by LGoldenDragon** [comment]
> ubuntu20.04, funasr&modelscope is last version. Lora finetune model can not decode:
> 
> RuntimeError：AutomaticSpeechRecognitionPipeline：Error（s）in loading state_dict for Paraformer： unexpected key(s) in state_dict: "encoder.encoders0.0.self_attn.linear_q_k_v.lora_A"

请问一下这个问题解决了吗？我也出现了这个问题
