### ISSUE TITLE
手动授权问题

### ISSUE THREAD

**Issue by westdata** [modelscope/FunASR#977]
Windows系统，chrome浏览器访问funasr的wss服务时，需要先点“手工授权（IOS）”，打开网页后，再连接才能成功。否则会报错。

**Comment by lukeewin** [comment]
你可以考虑用ws协议

**Comment by westdata** [comment]
> 你可以考虑用ws协议

ws协议如果不是用localhost访问，就直接报错了。

**Comment by zhaomingwork** [comment]
> Windows系统，chrome浏览器访问funasr的wss服务时，需要先点“手工授权（IOS）”，打开网页后，再连接才能成功。否则会报错。

是否需要授权和环境有关，目前提供手工授权就是为了解决这类问题。如有其他更好办法或建议，欢迎提出。

**Comment by chwyxy** [comment]
我现在想集成进入我的系统，每次都要点击手动授权吗，有没有别的办法可以避免这个问题

> > Windows系统，chrome浏览器访问funasr的wss服务时，需要先点“手工授权（IOS）”，打开网页后，再连接才能成功。否则会报错。
> 
> 是否需要授权和环境有关，目前提供手工授权就是为了解决这类问题。如有其他更好办法或建议，欢迎提出。

**Comment by yqp1453552101** [comment]
> > Windows系统，chrome浏览器访问funasr的wss服务时，需要先点“手工授权（IOS）”，打开网页后，再连接才能成功。否则会报错。
> 
> 是否需要授权和环境有关，目前提供手工授权就是为了解决这类问题。如有其他更好办法或建议，欢迎提出。

请问手工授权是授权了什么元素或协议吗

**Comment by chwyxy** [comment]
> > > Windows系统，chrome浏览器访问funasr的wss服务时，需要先点“手工授权（IOS）”，打开网页后，再连接才能成功。否则会报错。
> > 
> > 
> > 是否需要授权和环境有关，目前提供手工授权就是为了解决这类问题。如有其他更好办法或建议，欢迎提出。
> 
> 请问手工授权是授权了什么元素或协议吗

我最近貌似解决这个问题了，进容器把ssl证书关掉貌似可以了，启动的时候加上 --certfile 0

**Comment by yqp1453552101** [comment]
> > Windows系统，chrome浏览器访问funasr的wss服务时，需要先点“手工授权（IOS）”，打开网页后，再连接才能成功。否则会报错。
> 
> 是否需要授权和环境有关，目前提供手工授权就是为了解决这类问题。如有其他更好办法或建议，欢迎提出。

请问这个授权，授权的到底是啥，有没有研究过呢，谢谢
